const catalog = {
  'Oturma Grupları': {
    slug:'oturma', material:'Fırınlanmış gürgen iskelet / 32 DNS sünger / kolay temizlenir dokuma kumaş', dimensions:'Ürüne göre G 78–310 × D 82–165 × Y 75–92 cm', care:'Kumaşı düşük emiş gücünde süpürün. Lekeleri tampon hareketlerle, nötr sabunlu nemli bezle temizleyin.',
    names:['Vento Üçlü Koltuk','Luna İkili Koltuk','Terra Sağ Köşe Koltuk','Vento Yataklı Bazalı Koltuk','Arco Ahşap Kollu Berjer','Nora Sallanan Dinlenme Koltuğu','Mira Döner Berjer','Siena Deri Berjer','Noir Üçlü Koltuk','Sole İkili Koltuk','Pera Köşe Koltuk','Linea Bazalı Puf','Nord Lounge Berjer','Arco Sallanan Emzirme Koltuğu','Olive Döner Berjer','Mia Modüler Üçlü Koltuk','Atlas Deri Üçlü Koltuk','Riva Metal Ayaklı Berjer','Luna Organik Form Berjer','Olive İkili Koltuk','Noir Yataklı Köşe Koltuk','Nora Ahşap Kasalı Üçlü Koltuk','Mira Yuvarlak Puf','Terra Lounge Koltuk','Sole Sol Köşe Koltuk','Siena Döner Baba Koltuğu','Vento Tekli Modül Koltuk','Olive Sandıklı Puf','Noir Geniş Berjer','Luna Klasik İkili Koltuk']
  },
  'Salon Mobilyaları': {
    slug:'salon', material:'E1 kalite MDF / doğal ahşap kaplama / elektrostatik boyalı metal', dimensions:'Ürüne göre G 45–220 × D 35–90 × Y 42–190 cm', care:'Yüzeyi kuru veya hafif nemli mikrofiber bezle temizleyin. Sıcak yüzeyleri doğrudan temas ettirmeyin.',
    names:['Linea Ceviz TV Ünitesi 180 cm','Mira Krem TV Ünitesi 180 cm','Noir Mermer Desenli TV Ünitesi','Terra Meşe TV Sehpası','Sole Krem TV Konsolu','Nord Ceviz TV Ünitesi 210 cm','Mira Duvara Monte TV Ünitesi','Linea Duvara Monte Ceviz Ünite','Noir Duvara Monte TV Konsolu','Terra Duvara Monte TV Sehpası','Sole Duvara Monte Ünite','Nord Siyah TV Ünitesi','Arco Ceviz Orta Sehpa','Marmo Traverten Orta Sehpa','Luna Yuvarlak Orta Sehpa','Linea Cam Orta Sehpa','Terra Silindir Orta Sehpa','Noir Mermer Orta Sehpa','Nord 3’lü Zigon Sehpa','Marmo 2’li Zigon Sehpa','Sole Pirinç Zigon Sehpa','Pera C Yan Sehpa','Terra Ahşap Yan Sehpa','Noir Metal Yan Sehpa','Linea Ceviz Dresuar','Marmo Traverten Dresuar','Nord Ceviz Konsol','Sole Krem Konsol','Mira Cam Kapaklı Konsol','Terra Meşe Konsol']
  },
  'Yemek Odası': {
    slug:'yemek', material:'Masif kayın / doğal meşe veya ceviz kaplama / leke tutmaz kumaş', dimensions:'Masa seçenekleri G 120–220 × D 80–100 × Y 75 cm', care:'Ahşap yüzeyleri nemli bezle silip hemen kurulayın. Sandalye kumaşında kimyasal ağartıcı kullanmayın.',
    names:['Lina Meşe Yemek Masası 160 cm','Linea Ceviz Yemek Masası','Marmo Traverten Yemek Masası','Terra Oval Yemek Masası','Noir Siyah Yemek Masası','Nord Ceviz Oval Masa','Lina Açılır Yemek Masası','Noir Açılır Konsol Masa','Terra Açılır Ceviz Masa','Marmo Açılır Taş Masa','Nord Açılır Meşe Masa','Noir Açılır Yemek Masası','Arco Yuvarlak Meşe Masa','Terra Yuvarlak Ceviz Masa','Marmo Yuvarlak Traverten Masa','Nord Yuvarlak Ahşap Masa','Noir Yuvarlak Masa','Sole Yuvarlak Taş Masa','Lina 4 Kişilik Masa Takımı','Olive 4 Kişilik Masa Takımı','Terra Yuvarlak Masa Takımı','Noir Yuvarlak Masa Takımı','Mira 4 Kişilik Masa Takımı','Noir 4 Kişilik Masa Takımı','Lina 6 Kişilik Masa Takımı','Noir 6 Kişilik Masa Takımı','Terra 6 Kişilik Masa Takımı','Olive 6 Kişilik Masa Takımı','Nord 6 Kişilik Masa Takımı','Siena Yemek Odası Bench']
  },
  'Yatak Odası': {
    slug:'yatak', material:'E1 kalite MDF / fırınlanmış ahşap / metal taşıyıcı / dokuma kumaş', dimensions:'Karyola 160×200 cm; dolap ve tamamlayıcılarda modele göre değişir', care:'Mobilyayı doğrudan güneş ve nemden koruyun. Hareketli bağlantıları yılda bir kontrol edin.',
    names:['Luna Fitilli Karyola 160×200','Olive Fitilli Karyola 160×200','Nord Meşe Karyola 160×200','Linea Ceviz Karyola 160×200','Sole Döşemeli Karyola','Noir Döşemeli Karyola','Luna Bazalı Karyola','Olive Bazalı Karyola','Nord Ahşap Bazalı Karyola','Linea Ceviz Bazalı Karyola','Sole Sandıklı Baza','Noir Sandıklı Baza','Sole 6 Kapaklı Gardırop','Nord 5 Kapaklı Gardırop','Mira Aynalı Gardırop','Noir Cam Kapaklı Gardırop','Linea Sürgülü Gardırop','Terra Sürgülü Gardırop','Sole İki Çekmeceli Komodin','Nord Ceviz Komodin','Mira Modern Komodin','Linea Ceviz Komodin','Sole 3 Çekmeceli Şifonyer','Terra 6 Çekmeceli Şifonyer','Mira Makyaj Masası','Nord Aynalı Makyaj Masası','Sole Metal Ayaklı Makyaj Masası','Luna Yatak Ucu Bench','Olive Yatak Ucu Bench','Sole 5 Parça Yatak Odası Takımı']
  },
  'Çalışma & Depolama': {
    slug:'ofis', material:'E1 kalite yonga levha veya MDF / elektrostatik boyalı metal / ergonomik file', dimensions:'Ürüne göre G 60–180 × D 30–80 × Y 45–200 cm', care:'Bağlantıları düzenli kontrol edin. Ahşap yüzeyi nemli bezle, file döşemeyi düşük emişte süpürgeyle temizleyin.',
    names:['Atlas Çekmeceli Çalışma Masası','Lina 3 Çekmeceli Çalışma Masası','Nord Bilgisayar Masası','Linea L Köşe Çalışma Masası','Mira Metal Ayaklı Çalışma Masası','Terra Dolaplı Çalışma Masası','Noir Ergonomik Ofis Koltuğu','Mira Gri Ergonomik Koltuk','Olive Ergonomik Çalışma Koltuğu','Atlas Fileli Yönetici Koltuğu','Sole Deri Yönetici Koltuğu','Noir Deri Ofis Koltuğu','Nord 5 Raflı Kitaplık','Linea Cam Kapaklı Kitaplık','Atlas Metal Kitaplık','Mira Cam Kapaklı Dolap','Olive Metal Keson','Lina 3 Kapaklı Ayakkabılık','Nord Panjurlu Ayakkabılık','Sole Minderli Ayakkabılık','Mira Portmanto','Sole Aynalı Portmanto','Olive Banyo Dolabı','Lina Çok Amaçlı Mutfak Dolabı','Nord Mikrodalga Dolabı','Linea Katlanır Masa','Sole Katlanır Plastik Masa','Atlas Servis Arabası','Lina İnce Ayakkabılık','Nord Çok Amaçlı Dolap']
  }
};

const variantSets = {
  'Oturma Grupları':[['Krem Bukle','#e6ddcf'],['Vizon Keten','#9d8d7b'],['Zeytin Dokuma','#65705a'],['Kiremit Şönil','#a9583f'],['Antrasit Dokuma','#3d403d']],
  'Salon Mobilyaları':[['Ceviz','#76513c'],['Doğal Meşe','#c7a675'],['Krem','#e5ddcf'],['Antrasit','#40413e'],['Ceviz–Krem','#9b7a5c']],
  'Yemek Odası':[['Doğal Meşe','#c59b63'],['Ceviz','#6f4b38'],['Krem–Ceviz','#b49b7b'],['Siyah Meşe','#353632'],['Traverten','#d8c8ae']],
  'Yatak Odası':[['Krem–Ceviz','#c3a98a'],['Doğal Meşe','#c4a06f'],['Zeytin–Ceviz','#68705a'],['Antrasit–Ceviz','#494a47'],['Vizon–Meşe','#9b8975']],
  'Çalışma & Depolama':[['Ceviz–Siyah','#624b3b'],['Doğal Meşe–Beyaz','#cbb593'],['Antrasit–Ceviz','#474946'],['Zeytin–Meşe','#65705a'],['Tam Beyaz','#e5e3dd']]
};

const products=[]; let pid=1;
Object.entries(catalog).forEach(([category,group],categoryIndex)=>group.names.forEach((name,index)=>{
  const basePrices=[8999,3499,4999,5999,2999],priceSpans=[52000,30000,65000,80000,26000];
  const price=basePrices[categoryIndex]+((index*1703+categoryIndex*5431)%priceSpans[categoryIndex]); const discounted=(index+categoryIndex)%5===0;
  const assetStem=`${group.slug}-${String(index+1).padStart(2,'0')}`;
  products.push({id:pid++,name,category,image:`assets/furniture/variants/${assetStem}-v1.webp`,price,oldPrice:discounted?Math.round(price*1.22):null,rating:null,reviews:0,verifiedReviews:false,badge:discounted?'%18 İNDİRİM':'',fast:false,popular:false,deliveryVerified:false,popularityVerified:false,material:group.material,dimensions:group.dimensions,care:group.care,desc:`${name}; dayanıklı iskelet, günlük kullanım konforu ve zamansız çizgiyi bir araya getiren Viento mobilya koleksiyonunun karakterli parçalarından biridir. Ölçü, malzeme ve kullanım deneyimi birlikte değerlendirilerek hazırlanmıştır.`,variants:variantSets[category].map((v,i)=>({name:v[0],hex:v[1],image:`assets/furniture/variants/${assetStem}-v${i+1}.webp`,sku:`VNT-${String(categoryIndex+1).padStart(2,'0')}${String(index+1).padStart(2,'0')}-${i+1}`,stock:3+((index+i*5)%18)}))});
}));

function readStoreJSON(key,fallback){try{return JSON.parse(localStorage.getItem(key)||JSON.stringify(fallback))}catch{return fallback}}
function readStoreArray(key){const value=readStoreJSON(key,[]);return Array.isArray(value)?value:[]}
const remoteProducts=Array.isArray(window.VientoRemoteProducts)&&window.VientoRemoteProducts.length?window.VientoRemoteProducts:null;
if(remoteProducts)products.splice(0,products.length,...remoteProducts);
const adminOverrides=remoteProducts?{}:readStoreJSON('viento-admin-overrides',{});
products.forEach(product=>{
  const override=adminOverrides[product.id];
  if(!override)return;
  const seededImage=product.image,seededVariants=product.variants.map(v=>({...v}));
  Object.assign(product,override);
  const isLegacyImage=value=>!value||/^assets\/furniture\/[^/]+\.jpg$/i.test(value);
  if(isLegacyImage(override.image))product.image=seededImage;
  product.variants=seededVariants.map((seed,i)=>{
    const saved=override.variants?.[i]||{},clean={...saved};
    delete clean.filter;
    return{...seed,...clean,image:saved.filter||isLegacyImage(saved.image)?seed.image:saved.image};
  });
});
if(!remoteProducts)readStoreJSON('viento-admin-custom-products',[]).forEach(product=>products.push(product));
products.forEach((product,index)=>{
  product.id=Number(product.id)||index+1;product.name=String(product.name||'Adsız ürün');product.category=String(product.category||'Diğer');product.image=String(product.image||'');product.price=Math.max(0,Number(product.price)||0);product.oldPrice=Number(product.oldPrice)>product.price?Number(product.oldPrice):null;
  product.variants=(Array.isArray(product.variants)?product.variants:[]).map((variant,variantIndex)=>({...variant,name:String(variant?.name||`Varyasyon ${variantIndex+1}`),hex:String(variant?.hex||'#d8d2c8'),image:String(variant?.image||product.image),sku:String(variant?.sku||`VNT-${product.id}-${variantIndex+1}`),stock:Math.max(0,Number(variant?.stock)||0)}));
});
window.VientoAdminSeed=products;
function variantImage(product,variant){return variant?.image||product.image}

const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)], money=n=>new Intl.NumberFormat('tr-TR').format(n)+' TL';
const slugify=value=>String(value||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLocaleLowerCase('tr').replace(/ı/g,'i').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
const productSlug=product=>product.slug?slugify(product.slug):`${slugify(product.name)}-${Number(product.id)}`;
const defaultTitle=document.title,defaultDescription=document.querySelector('meta[name="description"]')?.content||'';
const productFromPath=()=>{const match=location.pathname.match(/^\/products\/([^/]+)\/?$/);if(!match)return null;try{const slug=decodeURIComponent(match[1]);return products.find(product=>productSlug(product)===slug)||null}catch{return null}};
function updateProductMeta(product){document.title=product?`${product.name} | Viento Market`:defaultTitle;const meta=document.querySelector('meta[name="description"]');if(meta)meta.content=product?String(product.seoDescription||product.desc||'').slice(0,160):defaultDescription}
const state={category:'Tümü',maxPrice:100000,discount:false,fast:false,popular:false,sort:'featured',visible:24,search:'',selectedProduct:null,selectedVariant:0,detailQty:1,gridView:+localStorage.getItem('viento-grid-view')||4,favorites:new Set(readStoreArray('viento-favs').map(Number).filter(Number.isFinite)),compare:new Set(readStoreArray('viento-compare').map(Number).filter(Number.isFinite).slice(0,3)),recent:readStoreArray('viento-recent').map(Number).filter(Number.isFinite).slice(0,8),cart:readStoreArray('viento-cart')};

function renderCatalogProofs(){const activeProducts=products.filter(product=>product.active!==false),variantTotal=activeProducts.reduce((total,product)=>total+(product.variants?.length||0),0),seating=activeProducts.filter(product=>product.category==='Oturma Grupları'),seatingVariants=seating.reduce((total,product)=>total+(product.variants?.length||0),0);if($('#catalogProof'))$('#catalogProof').textContent=`${activeProducts.length} mobilya · ${variantTotal} kayıtlı renk varyasyonu`;if($('#heroProductCount'))$('#heroProductCount').textContent=activeProducts.length;if($('#variantProof'))$('#variantProof').textContent=`${variantTotal} VARYASYON`;if($('#shopCatalogProof'))$('#shopCatalogProof').textContent=`${activeProducts.length} MOBİLYA · ${variantTotal} VARYASYON`;if($('#seatingProof'))$('#seatingProof').textContent=`${seating.length} tasarım · ${seatingVariants} renk seçeneği`;$$('[data-category-count]').forEach(element=>{element.textContent=`${activeProducts.filter(product=>product.category===element.dataset.categoryCount).length} ürün`});if($('#onlyFast')){$('#onlyFast').disabled=!activeProducts.some(product=>product.deliveryVerified===true);$('#onlyFast').closest('label').title=$('#onlyFast').disabled?'Doğrulanmış lojistik verisi bulunmuyor':''}if($('#onlyPopular')){$('#onlyPopular').disabled=!activeProducts.some(product=>product.popularityVerified===true);$('#onlyPopular').closest('label').title=$('#onlyPopular').disabled?'Doğrulanmış popülerlik verisi bulunmuyor':''}}

function filtered(){let list=products.filter(p=>p.active!==false&&(state.category==='Tümü'||p.category===state.category)&&p.price<=state.maxPrice&&(!state.discount||p.oldPrice)&&(!state.fast||p.deliveryVerified===true)&&(!state.popular||p.popularityVerified===true)&&(!state.search||(`${p.name} ${p.category}`).toLocaleLowerCase('tr').includes(state.search.toLocaleLowerCase('tr'))));if(state.sort==='low')list.sort((a,b)=>a.price-b.price);if(state.sort==='high')list.sort((a,b)=>b.price-a.price);if(state.sort==='new')list.sort((a,b)=>b.id-a.id);return list}
function colorDots(product){return(product.variants||[]).map(variant=>`<i title="${safeText(variant.name)}" style="background:${safeColor(variant.hex)}"></i>`).join('')}
function card(product){const id=Number(product.id),variants=Array.isArray(product.variants)?product.variants:[],badge=product.badge==='ÇOK SEVİLEN'&&product.popularityVerified!==true?'':product.badge;return`<article class="product-card" data-product="${id}" tabindex="0" aria-label="${safeText(product.name)} ürününü incele"><div class="product-image"><img loading="lazy" src="${safeText(product.image)}" alt="${safeText(product.name)}">${badge?`<span class="badge ${product.oldPrice?'sale-badge':''}">${safeText(badge)}</span>`:''}<button class="fav ${state.favorites.has(id)?'active':''}" data-fav="${id}" aria-label="Favoriye ekle">${state.favorites.has(id)?'♥':'♡'}</button><button class="compare-toggle ${state.compare.has(id)?'active':''}" data-compare="${id}" aria-label="Karşılaştırmaya ekle">⇄</button><button class="quick-btn" data-quick="${id}">Hızlı incele <span>↗</span></button></div><div class="product-meta"><div class="product-meta-top"><span class="product-category">${safeText(product.category)}</span>${product.deliveryVerified===true?'<span class="fast-delivery">Doğrulanmış hızlı teslimat</span>':''}</div><h3>${safeText(product.name)}</h3><div class="rating">${product.verifiedReviews&&Number(product.reviews)>0?`★★★★★ <span>${Number(product.rating)||0} (${Number(product.reviews)})</span>`:'<span>Henüz doğrulanmış değerlendirme yok</span>'}</div><div class="price">${money(Number(product.price)||0)} ${Number(product.oldPrice)?`<del>${money(Number(product.oldPrice))}</del>`:''}<small>Demo 6 taksit hesabı: ${money(Math.round((Number(product.price)||0)/6))}</small></div><div class="product-colors">${colorDots(product)}<small>${variants.length} renk</small></div></div></article>`}
function render(){const list=filtered(),shown=list.slice(0,state.visible),variantCount=list.reduce((sum,product)=>sum+(product.variants?.length||0),0);$('#productGrid').classList.toggle('grid-three',state.gridView===3);$('#productGrid').innerHTML=shown.map(card).join('');$('#resultCount').textContent=`${list.length} mobilya · ${variantCount} varyasyon`;$('#loadMore').style.display=shown.length<list.length?'block':'none';$('#loadMore span').textContent=`${shown.length} / ${list.length}`;$('#activeFilterCount').textContent=[state.category!=='Tümü',state.discount,state.fast,state.popular,state.maxPrice<100000].filter(Boolean).length;$$('[data-grid-view]').forEach(b=>b.classList.toggle('active',+b.dataset.gridView===state.gridView));bindCards()}
function bindCards(){$$('[data-fav]').forEach(b=>b.onclick=e=>{e.stopPropagation();toggleFav(+b.dataset.fav)});$$('[data-compare]').forEach(b=>b.onclick=e=>{e.stopPropagation();toggleCompare(+b.dataset.compare)});$$('[data-quick]').forEach(b=>b.onclick=e=>{e.stopPropagation();openProduct(+b.dataset.quick)});$$('[data-product]').forEach(c=>{c.onclick=e=>{if(!e.target.closest('button'))openProduct(+c.dataset.product)};c.onkeydown=e=>{if(e.key==='Enter')openProduct(+c.dataset.product)}})}
function setCategory(cat){state.category=cat;state.visible=24;$$('[data-chip]').forEach(b=>b.classList.toggle('active',b.dataset.chip===cat));$$('input[name=cat]').forEach(x=>x.checked=x.value===cat);render();$('#shop').scrollIntoView({behavior:'smooth'})}
function toggleFav(id){state.favorites.has(id)?state.favorites.delete(id):state.favorites.add(id);localStorage.setItem('viento-favs',JSON.stringify([...state.favorites]));$('#favCount').textContent=state.favorites.size;render();toast(state.favorites.has(id)?'Favorilere eklendi':'Favorilerden çıkarıldı')}
function toggleCompare(id){if(state.compare.has(id))state.compare.delete(id);else if(state.compare.size>=3){toast('En fazla 3 ürünü karşılaştırabilirsiniz');return}else state.compare.add(id);localStorage.setItem('viento-compare',JSON.stringify([...state.compare]));renderCompareBar();render();toast(state.compare.has(id)?'Karşılaştırmaya eklendi':'Karşılaştırmadan çıkarıldı')}
function renderCompareBar(){const selected=[...state.compare].map(id=>products.find(product=>Number(product.id)===Number(id))).filter(Boolean);$('#compareCount').textContent=selected.length;$('#compareThumbs').innerHTML=selected.map(product=>`<button data-compare-remove="${Number(product.id)}" title="${safeText(product.name)}"><img src="${safeText(product.image)}" alt="${safeText(product.name)}"><span>${safeText(product.name)}</span><i>×</i></button>`).join('')+Array.from({length:Math.max(0,3-selected.length)},()=>'<span class="compare-empty-slot">＋</span>').join('');$('#compareBar').classList.toggle('active',selected.length>0);$$('[data-compare-remove]').forEach(button=>button.onclick=()=>toggleCompare(+button.dataset.compareRemove));$('#compareOpen').disabled=selected.length<2}
function openCompare(){const selected=[...state.compare].map(id=>products.find(product=>Number(product.id)===Number(id))).filter(Boolean);if(selected.length<2)return toast('Karşılaştırmak için en az 2 ürün seçin');const rows=[['Fiyat',product=>money(Number(product.price)||0)],['Kategori',product=>product.category],['Ölçüler',product=>product.dimensions],['Malzeme',product=>product.material],['Renk seçeneği',product=>`${product.variants?.length||0} renk`],['Teslimat',()=>'Lojistik planında kesinleşir'],['Garanti',product=>product.warranty||'Belirtilmedi'],['Değerlendirme',product=>product.verifiedReviews&&Number(product.reviews)>0?`${Number(product.rating)||0} / 5 (${Number(product.reviews)})`:'Doğrulanmış değerlendirme yok']];$('#compareTable').innerHTML=`<div class="compare-grid compare-products"><span></span>${selected.map(product=>`<article><button data-compare-remove="${Number(product.id)}">×</button><img src="${safeText(product.image)}" alt="${safeText(product.name)}"><small>${safeText(product.category)}</small><h3>${safeText(product.name)}</h3><strong>${money(Number(product.price)||0)}</strong><button class="btn primary" data-compare-cart="${Number(product.id)}">Sepete ekle</button></article>`).join('')}</div>${rows.map(row=>`<div class="compare-grid compare-row"><b>${row[0]}</b>${selected.map(product=>`<span>${safeText(row[1](product))}</span>`).join('')}</div>`).join('')}`;$('#compareModal').classList.add('active');$('#overlay').classList.add('active');document.body.style.overflow='hidden';$$('#compareTable [data-compare-remove]').forEach(button=>button.onclick=()=>{toggleCompare(+button.dataset.compareRemove);openCompare()});$$('[data-compare-cart]').forEach(button=>button.onclick=()=>{closeAll();openProduct(+button.dataset.compareCart)})}
function openPanel(panel){$('#overlay').classList.add('active');panel.classList.add('active');panel.setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}
function closeAll(restoreProductUrl=true){$$('.drawer,.quick-view,.filters,.compare-modal').forEach(x=>{x.classList.remove('active');x.setAttribute('aria-hidden','true')});$('#overlay').classList.remove('active');document.body.style.overflow='';if(restoreProductUrl&&(location.pathname.startsWith('/products/')||location.hash.startsWith('#product-')))history.replaceState(null,'','/#shop');updateProductMeta(null)}
function renderVariant(){
  const p=state.selectedProduct,variants=Array.isArray(p?.variants)?p.variants:[],v=variants[state.selectedVariant]||variants[0];
  if(!p||!v)return;
  $('#qvImage').src=variantImage(p,v);$('#qvImage').style.removeProperty('filter');$('#selectedColor').textContent=v.name||'Renk belirtilmedi';
  const stock=Number(v.stock);$('#variantSku').textContent=`Ürün kodu: ${v.sku||'Belirtilmedi'} · ${Number.isFinite(stock)?`${Math.max(0,stock)} adet stokta`:'Stok bilgisi yok'}`;
  $$('[data-variant]').forEach((b,i)=>b.classList.toggle('active',i===state.selectedVariant));$$('[data-thumb]').forEach((b,i)=>b.classList.toggle('active',i===state.selectedVariant));
}
function openProduct(id,updateUrl=true){
  const p=products.find(product=>Number(product.id)===Number(id)),variants=Array.isArray(p?.variants)?p.variants:[];
  if(!p)return;
  if(!variants.length)return toast('Bu ürün için henüz satış varyasyonu tanımlanmamış');
  const productId=Number(p.id);if(updateUrl)history.pushState({productId},'',`/products/${productSlug(p)}`);updateProductMeta(p);state.selectedProduct=p;state.selectedVariant=0;state.detailQty=1;state.recent=[productId,...state.recent.filter(value=>Number(value)!==productId)].slice(0,8);localStorage.setItem('viento-recent',JSON.stringify(state.recent));
  $('#detailQty').textContent='1';$('#qvImage').src=variantImage(p,variants[0]);$('#qvImage').alt=p.name||'Viento ürünü';$('#qvBadge').textContent=p.badge||'';$('#qvCategory').textContent=p.category||'Kategori belirtilmedi';$('#qvBreadcrumb').textContent=`Ana Sayfa / ${p.category||'Ürünler'} / ${p.name||'Ürün'}`;$('#qvTitle').textContent=p.name||'Adsız ürün';
  $('#qvRating').innerHTML=p.verifiedReviews&&Number(p.reviews)>0?`<span>★★★★★</span> ${Number(p.rating)||0} · <u>${Number(p.reviews)} doğrulanmış değerlendirme</u>`:'<span>Henüz doğrulanmış değerlendirme yok</span>';
  const price=Number(p.price)||0,oldPrice=Number(p.oldPrice)||0;$('#qvPrice').innerHTML=`${money(price)} ${oldPrice?`<del>${money(oldPrice)}</del>`:''}<small>KDV dahil</small>`;$('#installmentLine').innerHTML=`Demo taksit hesabı · 6 eşit bölümde <b>aylık ${money(Math.round(price/6))}</b>`;$('#qvDescription').textContent=p.desc||'Ürün açıklaması henüz eklenmedi.';
  $('#qvSwatches').innerHTML=variants.map((variant,index)=>`<button class="swatch ${index===0?'active':''}" data-variant="${index}" style="--sw:${safeColor(variant.hex)}" aria-label="${safeText(variant.name||'Renk')}" title="${safeText(variant.name||'Renk')}"></button>`).join('');
  $('#qvThumbs').innerHTML=variants.map((variant,index)=>`<button data-thumb="${index}" class="${index===0?'active':''}"><img src="${safeText(variantImage(p,variant))}" alt="${safeText(`${p.name||'Ürün'} ${variant.name||'renk'}`)}"><span>${safeText(variant.name||'Renk')}</span></button>`).join('');
  const specs=[['Malzeme',p.material],['Ölçü',p.dimensions],['Renk seçeneği',`${variants.length} farklı renk`],['Garanti',p.warranty],['Menşei',p.origin]];$('#qvSpecs').innerHTML=specs.map(([label,value])=>`<div><dt>${label}</dt><dd>${safeText(value||'Belirtilmedi')}</dd></div>`).join('');$('#qvCare').textContent=p.care||'Bakım bilgisi henüz eklenmedi.';
  $('#qvFavorite').textContent=state.favorites.has(productId)?'♥ Favorilerde':'♡ Favorilere ekle';$('#qvCompare').textContent=state.compare.has(productId)?'✓ Karşılaştırmada':'⇄ Karşılaştır';$('#deliveryEstimateResult').textContent='';$$('[data-variant]').forEach(button=>button.onclick=()=>{state.selectedVariant=+button.dataset.variant;renderVariant()});$$('[data-thumb]').forEach(button=>button.onclick=()=>{state.selectedVariant=+button.dataset.thumb;renderVariant()});$('#qvAdd').onclick=addSelected;$('#qvFavorite').onclick=()=>{toggleFav(productId);$('#qvFavorite').textContent=state.favorites.has(productId)?'♥ Favorilerde':'♡ Favorilere ekle'};$('#qvCompare').onclick=()=>{toggleCompare(productId);$('#qvCompare').textContent=state.compare.has(productId)?'✓ Karşılaştırmada':'⇄ Karşılaştır'};renderVariant();openPanel($('#quickView'));
}
function addSelected(){const p=state.selectedProduct,variants=Array.isArray(p?.variants)?p.variants:[],v=variants[state.selectedVariant];if(!p||!v)return toast('Ürün varyasyonu bulunamadı');const key=`${Number(p.id)}-${state.selectedVariant}`,found=state.cart.find(item=>(item.key||`${item.id}-0`)===key);if(found)found.qty+=state.detailQty;else state.cart.push({key,id:Number(p.id),variant:state.selectedVariant,qty:state.detailQty});saveCart();closeAll();openCart();toast(`${v.name||'Seçili'} varyasyonu sepete eklendi`)}
function saveCart(){localStorage.setItem('viento-cart',JSON.stringify(state.cart));renderCart()}
function renderCart(){
  state.cart=state.cart.filter(item=>products.some(product=>Number(product.id)===Number(item.id)));
  const count=state.cart.reduce((total,item)=>total+Math.max(0,Number(item.qty)||0),0),subtotal=state.cart.reduce((total,item)=>{const product=products.find(entry=>Number(entry.id)===Number(item.id));return total+(Number(product?.price)||0)*Math.max(0,Number(item.qty)||0)},0);
  $('#cartCount').textContent=count;$('#mobileCartCount').textContent=count;$('#cartTitleCount').textContent=`(${count})`;$('#cartSubtotal').textContent=money(subtotal);$('#shippingBar').style.width='0%';$('#shippingText').textContent='Teslimat süresi ve ücreti adres onayında planlanır.';
  $('#cartItems').innerHTML=state.cart.map(item=>{const product=products.find(entry=>Number(entry.id)===Number(item.id)),variants=Array.isArray(product?.variants)?product.variants:[],variant=variants[Number(item.variant)||0]||variants[0]||{},key=item.key||`${Number(item.id)}-0`,qty=Math.max(1,Number(item.qty)||1);return `<div class="cart-item"><img src="${safeText(variantImage(product,variant))}" alt="${safeText(`${product?.name||'Ürün'} ${variant.name||''}`)}"><div><h4>${safeText(product?.name||'Adsız ürün')}</h4><small>${safeText(variant.name||'Varyasyon belirtilmedi')} · ${safeText(variant.sku||'Kod yok')}</small><div class="qty"><button data-qty="${safeText(key)}" data-d="-1">−</button><span>${qty}</span><button data-qty="${safeText(key)}" data-d="1">+</button></div><button class="remove" data-remove="${safeText(key)}">Kaldır</button></div><strong>${money((Number(product?.price)||0)*qty)}</strong></div>`}).join('');
  $('#cartEmpty').style.display=count?'none':'block';$('#cartFooter').style.display=count?'block':'none';$$('[data-qty]').forEach(button=>button.onclick=()=>changeQty(button.dataset.qty,+button.dataset.d));$$('[data-remove]').forEach(button=>button.onclick=()=>{state.cart=state.cart.filter(item=>(item.key||`${item.id}-0`)!==button.dataset.remove);saveCart()});
}
function changeQty(key,d){const x=state.cart.find(x=>(x.key||`${x.id}-0`)===key);if(!x)return;x.qty+=d;if(x.qty<1)state.cart=state.cart.filter(y=>y!==x);saveCart()}
function openCart(){openPanel($('#cartDrawer'))}
const safeText=value=>String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
const safeColor=value=>/^#[0-9a-f]{3,8}$/i.test(String(value||''))?String(value):'#d8d2c8';
let customerAccount=null,authMode='login',accountLoading=false;
function setAccountMessage(message,type=''){$('#accountMessage').textContent=message||'';$('#accountMessage').className=`account-message ${type}`}
function orderStage(status){if(status==='Teslim edildi')return 4;if(status==='Gönderildi')return 3;if(['Hazırlanıyor','Ödendi'].includes(status))return 2;return 1}
function renderCustomerOrders(orders=[]){
  const container=$('#accountOrders');
  if(!orders.length){container.innerHTML='<div class="account-empty">Henüz siparişiniz yok. İlk Viento parçanızı keşfedin.</div>';return}
  container.innerHTML=orders.map(order=>{const stage=orderStage(order.status),cancelled=order.status==='İptal',provider=order.payment_provider==='paytr_demo'?'PayTR demo':order.payment_provider==='iyzico_demo'?'iyzico demo':'Demo ödeme',date=new Date(order.date),dateLabel=Number.isNaN(date.getTime())?'Tarih belirtilmedi':new Intl.DateTimeFormat('tr-TR',{day:'numeric',month:'long',year:'numeric'}).format(date);return`<article class="account-order"><div class="account-order-head"><span><b>#${safeText(order.order_id)}</b><small>${dateLabel} · ${safeText(order.payment)}</small></span><strong>${money(Number(order.total)||0)}</strong></div>${cancelled?'<div class="account-tracking"><b>Sipariş iptal edildi</b><span>Ekibimiz sizinle iletişime geçecek.</span></div>':`<div class="order-status-line">${['Sipariş alındı','Hazırlanıyor','Gönderildi','Teslim edildi'].map((label,i)=>`<span class="${i<stage?'done':''}">${label}</span>`).join('')}</div>`}${order.tracking_number?`<div class="account-tracking"><span><small>KARGO</small><b>${safeText(order.tracking_company||'Kargo firması')}</b></span><span><small>TAKİP NUMARASI</small><b>${safeText(order.tracking_number)}</b></span></div>`:''}<div class="account-order-products">${Array.isArray(order.items)?order.items.reduce((sum,item)=>sum+Math.max(0,Number(item.qty)||0),0):0} ürün · ${safeText(order.status)}${order.payment_reference?` · ${provider} / ${safeText(order.payment_reference)}`:''}</div></article>`}).join('')
}
function renderCustomerAddresses(addresses=[]){
  const container=$('#accountAddresses');
  container.innerHTML=addresses.length?addresses.map(address=>`<article class="account-address"><div><b>${safeText(address.title)}</b><p>${safeText(address.address)}<br>${safeText(address.district)} / ${safeText(address.city)} ${safeText(address.postcode)}</p></div>${address.is_default?'<em>VARSAYILAN</em>':'<span></span>'}<button type="button" data-delete-address="${safeText(address.id)}">Adresi sil</button></article>`).join(''):'<div class="account-empty">Kayıtlı teslimat adresiniz bulunmuyor.</div>';
  $$('[data-delete-address]').forEach(button=>button.onclick=async()=>{if(!confirm('Bu adres silinsin mi?'))return;try{await window.VientoAuth.deleteCustomerAddress(button.dataset.deleteAddress);await refreshCustomerAccount();toast('Adres silindi')}catch(error){toast(error.message)}})
}
function initialsForCustomer(name){return String(name||'Viento Müşteri').split(/\s+/).filter(Boolean).slice(0,2).map(part=>part[0]).join('').toLocaleUpperCase('tr')}
function renderCustomerAccount(){
  const signed=Boolean(customerAccount?.user);$('#accountAuthView').hidden=signed;$('#accountSignedView').hidden=!signed;$('#accountBtn').classList.toggle('signed',signed);$('#accountBtnText').textContent=signed?'Hesabım':'Giriş';
  if(!signed)return;
  const profile=customerAccount.profile||{},name=profile.full_name||customerAccount.user.user_metadata?.full_name||'Viento üyesi';$('#accountName').textContent=name;$('#accountEmail').textContent=customerAccount.user.email||'';$('#accountAvatar').textContent=initialsForCustomer(name);$('#accountOrderCount').textContent=customerAccount.orders.length;$('#accountAddressCount').textContent=customerAccount.addresses.length;const profileForm=$('#customerProfileForm');profileForm.elements.full_name.value=profile.full_name||'';profileForm.elements.phone.value=profile.phone||'';renderCustomerOrders(customerAccount.orders);renderCustomerAddresses(customerAccount.addresses)
}
async function refreshCustomerAccount(){
  if(accountLoading)return customerAccount;accountLoading=true;
  try{customerAccount=await window.VientoAuth.getCustomerAccount();renderCustomerAccount();return customerAccount}catch(error){console.error(error);setAccountMessage(error.message)}finally{accountLoading=false}
}
async function openAccount(){closeAll();openPanel($('#accountDrawer'));await refreshCustomerAccount()}
function setAuthMode(mode){authMode=mode;$('#accountAuthView').classList.toggle('signup',mode==='signup');$$('[data-auth-mode]').forEach(button=>button.classList.toggle('active',button.dataset.authMode===mode));$('#customerAuthSubmit').textContent=mode==='signup'?'Üyeliğimi oluştur':'Giriş yap';$('#customerAuthForm').elements.password.autocomplete=mode==='signup'?'new-password':'current-password';setAccountMessage('')}
function prefillCheckout(){
  if(!customerAccount)return;const form=$('#checkoutForm'),profile=customerAccount.profile||{},parts=String(profile.full_name||'').trim().split(/\s+/);form.elements.email.value=customerAccount.user.email||'';form.elements.firstName.value=parts.shift()||'';form.elements.lastName.value=parts.join(' ');form.elements.phone.value=profile.phone||'';const address=customerAccount.addresses.find(item=>item.is_default)||customerAccount.addresses[0];if(address){form.elements.address.value=address.address||'';form.elements.city.value=address.city||'İstanbul';form.elements.district.value=address.district||'';form.elements.postcode.value=address.postcode||''}
}
let checkoutStep=1;
function checkoutSubtotal(){return state.cart.reduce((total,item)=>total+(Number(products.find(product=>Number(product.id)===Number(item.id))?.price)||0)*Math.max(0,Number(item.qty)||0),0)}
function renderCheckout(){
  const subtotal=checkoutSubtotal();
  $('#checkoutItems').innerHTML=state.cart.map(item=>{const product=products.find(entry=>Number(entry.id)===Number(item.id)),variants=Array.isArray(product?.variants)?product.variants:[],variant=variants[Number(item.variant)||0]||variants[0]||{},qty=Math.max(1,Number(item.qty)||1);return`<article><img src="${safeText(variantImage(product,variant))}" alt="${safeText(`${product?.name||'Ürün'} ${variant.name||''}`)}"><span><b>${safeText(product?.name||'Adsız ürün')}</b><small>${safeText(variant.name||'Varyasyon belirtilmedi')} · ${qty} adet</small></span><strong>${money((Number(product?.price)||0)*qty)}</strong></article>`}).join('');
  $('#checkoutSubtotal').textContent=$('#checkoutTotal').textContent=money(subtotal);$$('[data-checkout-step]').forEach(element=>element.classList.toggle('active',+element.dataset.checkoutStep===checkoutStep));$$('[data-checkout-progress]').forEach(element=>{element.classList.toggle('active',+element.dataset.checkoutProgress<=checkoutStep);element.classList.toggle('current',+element.dataset.checkoutProgress===checkoutStep)});$('#checkoutBack').style.visibility=checkoutStep===1?'hidden':'visible';$('#checkoutNext').textContent=checkoutStep===3?`${money(subtotal)} · Demo ödemeyi çalıştır`:checkoutStep===1?'Teslimata devam et':'Demo ödemeye devam et';
}
async function openCheckout(){if(!state.cart.length)return toast('Sepetiniz henüz boş');if(!customerAccount?.user)await refreshCustomerAccount();if(!customerAccount?.user){await openAccount();setAccountMessage('Demo ödeme ve sipariş takibi için giriş yapın veya ücretsiz üye olun.');return}closeAll();checkoutStep=1;prefillCheckout();renderCheckout();$('#checkoutModal').classList.add('active');document.body.style.overflow='hidden'}
function closeCheckout(){$('#checkoutModal').classList.remove('active');document.body.style.overflow=''}
function validateCheckoutStep(){const step=$(`[data-checkout-step="${checkoutStep}"]`),fields=$$('input[required],select[required]').filter(x=>step.contains(x));for(const field of fields){if(!field.checkValidity()){field.reportValidity();return false}}return true}
async function completeCheckout(){if(!validateCheckoutStep())return;const form=$('#checkoutForm'),data=new FormData(form),button=$('#checkoutNext'),original=button.textContent,order={customer:`${data.get('firstName')} ${data.get('lastName')}`.trim(),email:data.get('email'),phone:data.get('phone'),city:data.get('city'),district:data.get('district'),address:data.get('address'),postcode:data.get('postcode'),items:state.cart.map(x=>({id:x.id,variant:x.variant||0,qty:x.qty})),notes:data.get('floor')||''},provider=data.get('paymentProvider'),scenario=data.get('demoScenario');button.disabled=true;button.textContent='Demo sanal POS çalışıyor…';try{const result=await window.VientoDB.demoCheckout(order,provider,scenario);if(!result.success){toast(`Demo ödeme reddedildi · ${result.reference}`);return}state.cart=[];saveCart();form.elements.demoCard.value='';form.elements.demoExpiry.value='';form.elements.demoCvv.value='';closeCheckout();form.reset();await refreshCustomerAccount();toast(`Demo ödeme başarılı · Sipariş #${result.id}`)}catch(error){console.error(error);toast(`Demo işlem tamamlanamadı: ${error.message}`)}finally{button.disabled=false;button.textContent=original}}
let toastTimer;function toast(msg){$('#toast').textContent=msg;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),2200)}
const roomProductIds=[1,37,46];
function hydrateProductHotspots(){
  $$('[data-hero-product],[data-room-product]').forEach(button=>{
    const id=Number(button.dataset.heroProduct||button.dataset.roomProduct),product=products.find(entry=>Number(entry.id)===id),label=button.querySelector('span');
    if(!product||!label){button.hidden=true;return}
    button.hidden=false;
    if(button.dataset.heroProduct){const name=label.querySelector('b'),price=label.querySelector('small');if(name)name.textContent=product.name;if(price)price.textContent=money(product.price)}
    else label.innerHTML=`${safeText(product.name)}<br><b>${money(product.price)}</b>`;
    button.setAttribute('aria-label',`${product.name} ürününü incele`);
  });
}
function renderRoomExperience(){const room=roomProductIds.map(id=>products.find(product=>Number(product.id)===id)).filter(Boolean);$('#roomProducts').innerHTML=room.map(product=>`<button data-room-list-product="${Number(product.id)}"><img src="${safeText(product.image)}" alt="${safeText(product.name)}"><span><b>${safeText(product.name)}</b><small>${safeText(product.category)}</small></span><strong>${money(Number(product.price)||0)}</strong></button>`).join('');$$('[data-room-list-product]').forEach(button=>button.onclick=()=>openProduct(+button.dataset.roomListProduct))}
function renderSmartPicks(){if(!products.length){$('#smartPicks').innerHTML='<p class="empty-state">Önerilecek aktif ürün bulunmuyor.</p>';return}const recentIndex=Math.max(0,products.findIndex(product=>Number(product.id)===Number(state.recent[0]))),offsets=[7,31,62,94,121],list=offsets.map(offset=>products[(recentIndex+offset)%products.length]).filter((product,index,array)=>product&&array.findIndex(item=>item.id===product.id)===index);$('#smartPicks').innerHTML=list.map(card).join('');bindCards()}

const serviceContent={
  consultation:{title:'İç mimari danışmanlık',description:'Mekân ölçünüzü, ihtiyaçlarınızı ve uygun olduğunuz zamanı paylaşın.'},
  sample:{title:'Kumaş ve renk numunesi',description:'İlgilendiğiniz ürünleri veya renkleri yazın; numune seçeneklerini birlikte planlayalım.'},
  delivery:{title:'Teslimat ve kurulum',description:'Ürün, şehir ve teslimat ihtiyacınızı paylaşın; ekibimiz planlama konusunda sizi arasın.'}
};
function setFormMessage(selector,message,type=''){const output=$(selector);output.textContent=message;output.className=type}
function openServiceRequest(service){const content=serviceContent[service]||serviceContent.consultation,form=$('#serviceRequestForm');form.elements.service.value=service;$('#serviceTitle').textContent=content.title;$('#serviceDescription').textContent=content.description;setFormMessage('#serviceRequestMessage','');openPanel($('#serviceDrawer'));setTimeout(()=>form.elements.name.focus(),120)}

if($('#productGrid')){
$('#cartBtn').onclick=openCart;$('#accountBtn').onclick=openAccount;$('#mobileAccount').onclick=openAccount;$('#searchBtn').onclick=()=>openPanel($('#searchDrawer'));$('#overlay').onclick=closeAll;$$('[data-close]').forEach(b=>b.onclick=closeAll);$('#loadMore').onclick=()=>{state.visible+=24;render()};$('#sortSelect').onchange=e=>{state.sort=e.target.value;render()};$('#priceRange').oninput=e=>{$('#priceValue').textContent=money(+e.target.value)};$$('[data-grid-view]').forEach(b=>b.onclick=()=>{state.gridView=+b.dataset.gridView;localStorage.setItem('viento-grid-view',state.gridView);render()});
$('#applyFilters').onclick=()=>{const cats=$$('input[name=cat]:checked').map(x=>x.value);state.category=cats[0]||'Tümü';state.maxPrice=+$('#priceRange').value;state.discount=$('#onlyDiscount').checked;state.fast=$('#onlyFast').checked;state.popular=$('#onlyPopular').checked;state.visible=24;closeAll();render()};
$('#clearFilters').onclick=()=>{state.category='Tümü';state.maxPrice=100000;state.discount=state.fast=state.popular=false;$$('.filters input[type=checkbox]').forEach(x=>x.checked=false);$('#priceRange').value=100000;$('#priceValue').textContent='100.000 TL';render()};$('#filterToggle').onclick=()=>openPanel($('#filters'));$('#filterClose').onclick=closeAll;
$$('[data-chip]').forEach(b=>b.onclick=()=>setCategory(b.dataset.chip));$$('[data-category]').forEach(b=>b.onclick=()=>setCategory(b.dataset.category));$$('[data-nav-category]').forEach(a=>a.onclick=e=>{e.preventDefault();setCategory(a.dataset.navCategory==='Fırsatlar'?'Tümü':a.dataset.navCategory);if(a.dataset.navCategory==='Fırsatlar'){state.discount=true;render()}});$('[data-filter-preset]').onclick=e=>{e.preventDefault();state.popular=true;setCategory('Tümü')};
$('#searchInput').oninput=event=>{state.search=event.target.value;const list=filtered().slice(0,8);$('#searchResults').innerHTML=list.length?list.map(product=>`<button class="search-result" data-search-product="${Number(product.id)}"><img src="${safeText(product.image)}" alt="${safeText(product.name)}"><span><h4>${safeText(product.name)}</h4><small>${safeText(product.category)} · ${product.variants?.length||0} renk</small></span><b>${money(Number(product.price)||0)}</b></button>`).join(''):'<p>Aramanızla eşleşen mobilya bulunamadı.</p>';$$('[data-search-product]').forEach(button=>button.onclick=()=>{closeAll();openProduct(+button.dataset.searchProduct)})};$('#searchClear').onclick=()=>{$('#searchInput').value='';state.search='';$('#searchResults').innerHTML=''};$$('[data-search]').forEach(button=>button.onclick=()=>{$('#searchInput').value=button.dataset.search;$('#searchInput').dispatchEvent(new Event('input'))});
$('#detailMinus').onclick=()=>{state.detailQty=Math.max(1,state.detailQty-1);$('#detailQty').textContent=state.detailQty};$('#detailPlus').onclick=()=>{state.detailQty=Math.min(10,state.detailQty+1);$('#detailQty').textContent=state.detailQty};
$$('[data-accordion]').forEach(b=>b.onclick=()=>{const panel=$(`#${b.dataset.accordion}`),open=panel.classList.toggle('open');b.classList.toggle('open',open);b.querySelector('span').textContent=open?'−':'+'});
$('#zoomBtn').onclick=()=>$('#qvImage').classList.toggle('zoomed');$('#menuBtn').onclick=()=>$('#mobileNav').classList.toggle('active');$('#newsletterForm').onsubmit=async event=>{event.preventDefault();const form=event.currentTarget,button=form.querySelector('button'),email=new FormData(form).get('email');button.disabled=true;setFormMessage('#newsletterMessage','Kaydınız alınıyor…');try{const result=await window.VientoDB.subscribeNewsletter(email);form.reset();setFormMessage('#newsletterMessage',result.existing?'Bu e-posta zaten kayıtlı.':'Kaydınız alındı. Hoş geldiniz!','success')}catch(error){setFormMessage('#newsletterMessage',error.message)}finally{button.disabled=false}};$('#checkoutBtn').onclick=openCheckout;$('#checkoutClose').onclick=closeCheckout;$('#checkoutBack').onclick=()=>{checkoutStep=Math.max(1,checkoutStep-1);renderCheckout()};$('#checkoutNext').onclick=()=>{if(!validateCheckoutStep())return;if(checkoutStep<3){checkoutStep++;renderCheckout()}else completeCheckout()};$('#checkoutForm').onsubmit=e=>e.preventDefault();$$('input[name="paymentProvider"]').forEach(input=>input.onchange=()=>{$$('.demo-provider').forEach(label=>label.classList.toggle('active',label.contains(input)&&input.checked));$('#demoCardBrand').textContent=input.value==='paytr_demo'?'PayTR demo':'iyzico demo'});
$$('[data-auth-mode]').forEach(button=>button.onclick=()=>setAuthMode(button.dataset.authMode));
$('#customerAuthForm').onsubmit=async event=>{event.preventDefault();const form=event.currentTarget,data=new FormData(form),button=$('#customerAuthSubmit');button.disabled=true;setAccountMessage(authMode==='signup'?'Üyeliğiniz oluşturuluyor…':'Giriş yapılıyor…');try{if(authMode==='signup'){const result=await window.VientoAuth.signUp({email:data.get('email'),password:data.get('password'),fullName:data.get('fullName'),phone:data.get('phone')});if(!result.session){setAccountMessage('Doğrulama bağlantısı e-posta adresinize gönderildi. Bağlantıdan sonra hesabınıza giriş yapabilirsiniz.','success');return}}else await window.VientoAuth.signIn(data.get('email'),data.get('password'));form.reset();customerAccount=null;await refreshCustomerAccount();setAccountMessage('')}catch(error){setAccountMessage(error.message)}finally{button.disabled=false}};
$('#googleAuth').onclick=async()=>{setAccountMessage('Google oturumu açılıyor…');try{await window.VientoAuth.signInWithGoogle()}catch(error){setAccountMessage(`Google girişi henüz Supabase sağlayıcı ayarı istiyor: ${error.message}`)}};
$('#customerLogout').onclick=async()=>{await window.VientoAuth.signOut();customerAccount=null;renderCustomerAccount();toast('Oturum kapatıldı')};$('#refreshAccount').onclick=()=>refreshCustomerAccount();
$('#customerProfileForm').onsubmit=async event=>{event.preventDefault();const data=new FormData(event.currentTarget);try{await window.VientoAuth.saveCustomerProfile(Object.fromEntries(data));await refreshCustomerAccount();toast('Profil bilgileri kaydedildi')}catch(error){toast(error.message)}};
$('#customerAddressForm').onsubmit=async event=>{event.preventDefault();const data=new FormData(event.currentTarget),values=Object.fromEntries(data);values.is_default=data.get('is_default')==='on';try{await window.VientoAuth.saveCustomerAddress(values);event.currentTarget.reset();event.currentTarget.elements.title.value='Ev';await refreshCustomerAccount();toast('Teslimat adresi kaydedildi')}catch(error){toast(error.message)}};
$('#compareOpen').onclick=openCompare;$('#compareClose').onclick=closeAll;$('#compareClear').onclick=()=>{state.compare.clear();localStorage.setItem('viento-compare','[]');renderCompareBar();render()};$('#qvShare').onclick=async()=>{const text=`${state.selectedProduct?.name||'Viento ürünü'} · ${location.href}`;try{if(navigator.share)await navigator.share({title:state.selectedProduct.name,text,url:location.href});else await navigator.clipboard.writeText(text);toast('Ürün bağlantısı kopyalandı')}catch{toast('Paylaşım iptal edildi')}};$('#deliveryEstimator').onsubmit=event=>{event.preventDefault();const code=$('#deliveryPostcode').value.trim();if(!/^\d{5}$/.test(code))return toast('5 haneli posta kodu girin');$('#deliveryEstimateResult').textContent='Teslimat süresi, lojistik sağlayıcısı ve adres uygunluğu doğrulandığında hesaplanacak.'};
$$('[data-hero-product]').forEach(button=>button.onclick=()=>openProduct(+button.dataset.heroProduct));$$('[data-room-product]').forEach(button=>button.onclick=()=>openProduct(+button.dataset.roomProduct));$$('[data-discovery-category]').forEach(card=>card.onclick=()=>setCategory(card.dataset.discoveryCategory));$$('[data-discovery-trigger]').forEach(button=>button.onclick=event=>{event.stopPropagation();setCategory(button.closest('[data-discovery-category]').dataset.discoveryCategory)});$$('[data-scroll-shop]').forEach(button=>button.onclick=()=>$('#shop').scrollIntoView({behavior:'smooth'}));$('#addRoomToCart').onclick=()=>{let added=0;roomProductIds.forEach(id=>{const product=products.find(entry=>Number(entry.id)===id);if(!product||!product.variants?.length)return;const key=`${id}-0`,found=state.cart.find(item=>(item.key||`${item.id}-0`)===key);found?found.qty++:state.cart.push({key,id,variant:0,qty:1});added++});if(!added)return toast('Bu oda için sepete eklenebilir ürün bulunamadı');saveCart();openCart();toast(`Odadaki ${added} ürün sepete eklendi`)};$('#roomPlanner').onclick=()=>{const active=$('.room-stage').classList.toggle('planning');$('#roomPlanner').textContent=active?'▧ Ürün noktalarını gizle':'▧ Ürün noktalarını göster'};
$('#smartPrev').onclick=()=>$('#smartPicks').scrollBy({left:-420,behavior:'smooth'});$('#smartNext').onclick=()=>$('#smartPicks').scrollBy({left:420,behavior:'smooth'});$$('[data-service]').forEach(b=>b.onclick=()=>openServiceRequest(b.dataset.service));$('#serviceRequestForm').onsubmit=async event=>{event.preventDefault();const form=event.currentTarget,button=$('#serviceRequestSubmit'),values=Object.fromEntries(new FormData(form));button.disabled=true;setFormMessage('#serviceRequestMessage','Talebiniz kaydediliyor…');try{await window.VientoDB.submitServiceRequest(values);const service=values.service;form.reset();form.elements.service.value=service;setFormMessage('#serviceRequestMessage','Talebiniz alındı. Ekibimiz sizinle iletişime geçecek.','success')}catch(error){setFormMessage('#serviceRequestMessage',error.message)}finally{button.disabled=false}};$('#mobileSearch').onclick=()=>openPanel($('#searchDrawer'));$('#mobileCart').onclick=openCart;document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();openPanel($('#searchDrawer'));setTimeout(()=>$('#searchInput').focus(),200)}if(e.key==='Escape'){closeAll();closeCheckout()}});
$('#favBtn').onclick=()=>{const favs=products.filter(p=>state.favorites.has(p.id));closeAll();$('#productGrid').innerHTML=favs.length?favs.map(card).join(''):'<p class="empty-state">Henüz favoriniz yok.</p>';$('#resultCount').textContent=`${favs.length} favori`;$('#loadMore').style.display='none';$('#shop').scrollIntoView({behavior:'smooth'});bindCards()};
$('#favCount').textContent=state.favorites.size;renderCatalogProofs();hydrateProductHotspots();renderCart();renderCompareBar();renderRoomExperience();renderSmartPicks();render();
const revealObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('revealed');revealObserver.unobserve(entry.target)}}),{threshold:.08});$$('.section,.trend-strip,.story,.service-suite').forEach(el=>{el.classList.add('reveal-ready');revealObserver.observe(el)});
setTimeout(()=>$$('.reveal-ready').forEach(el=>el.classList.add('revealed')),700);
const adminContent=readStoreJSON('viento-admin-content',{}),announcementBar=$('#announcementBar');if(adminContent.announcementText)announcementBar.textContent=adminContent.announcementText;if(adminContent.announcementActive===false)announcementBar.closest('.topbar').style.display='none';const announcementTarget=String(adminContent.announcementLink||'#shop').trim();if(announcementTarget.startsWith('#')||/^https?:\/\//i.test(announcementTarget)){announcementBar.setAttribute('role','link');announcementBar.tabIndex=0;const openAnnouncement=()=>{if(announcementTarget.startsWith('#'))location.hash=announcementTarget;else location.assign(announcementTarget)};announcementBar.onclick=openAnnouncement;announcementBar.onkeydown=event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();openAnnouncement()}}}if(adminContent.heroEyebrow)$('.hero .eyebrow').textContent=adminContent.heroEyebrow;if(adminContent.heroTitle)$('.hero h1').textContent=adminContent.heroTitle;if(adminContent.heroDescription)$('.hero-copy>p:not(.eyebrow)').textContent=adminContent.heroDescription;
window.VientoAuth.onAuthStateChange(()=>{customerAccount=null;setTimeout(()=>refreshCustomerAccount(),0)});refreshCustomerAccount();if(location.hash==='#account')setTimeout(openAccount,100);
const initialProduct=productFromPath();if(initialProduct)setTimeout(()=>openProduct(initialProduct.id,false),0);else if(location.hash.startsWith('#product-'))setTimeout(()=>openProduct(+location.hash.replace('#product-',''),true),0);
window.addEventListener('popstate',()=>{const product=productFromPath();if(product)openProduct(product.id,false);else closeAll(false)});
}
