const catalog = {
  'Oturma Grupları': {
    slug:'oturma', material:'Fırınlanmış gürgen iskelet / 32 DNS sünger / kolay temizlenir dokuma kumaş', dimensions:'Ürüne göre G 78–310 × D 82–165 × Y 75–92 cm', care:'Kumaşı düşük emiş gücünde süpürün. Lekeleri tampon hareketlerle, nötr sabunlu nemli bezle temizleyin.',
    names:['Vento Üçlü Koltuk','Luna İkili Koltuk','Terra Sağ Köşe Koltuk','Vento Yataklı Bazalı Koltuk','Arco Ahşap Kollu Berjer','Nora Sallanan Dinlenme Koltuğu','Mira Döner Berjer','Siena Deri Berjer','Noir Üçlü Koltuk','Sole İkili Koltuk','Pera Köşe Koltuk','Linea Bazalı Puf','Nord Lounge Berjer','Arco Sallanan Emzirme Koltuğu','Olive Döner Berjer','Mia Modüler Üçlü Koltuk','Atlas Deri Üçlü Koltuk','Riva Metal Ayaklı Berjer','Luna Organik Form Berjer','Olive İkili Koltuk','Noir Yataklı Köşe Koltuk','Nora Ahşap Kasalı Üçlü Koltuk','Mira Yuvarlak Puf','Terra Lounge Koltuk','Sole Sol Köşe Koltuk','Siena Döner Baba Koltuğu','Vento Tekli Modül Koltuk','Olive Sandıklı Puf','Noir Geniş Berjer','Luna Klasik İkili Koltuk']
  },
  'Salon Mobilyaları': {
    slug:'salon', material:'E1 kalite MDF / doğal ahşap kaplama / elektrostatik boyalı metal', dimensions:'Ürüne göre G 45–220 × D 35–90 × Y 42–190 cm', care:'Yüzeyi kuru veya hafif nemli mikrofiber bezle temizleyin. Sıcak yüzeyleri doğrudan temas ettirmeyin.',
    names:['Linea Ceviz TV Ünitesi 180 cm','Mira Krem TV Ünitesi 180 cm','Noir Mermer Desenli TV Ünitesi','Terra Meşe TV Sehpası','Sole Krem TV Konsolu','Nord Ceviz TV Ünitesi 210 cm','Mira Duvara Monte TV Ünitesi','Linea Duvara Monte Ceviz Ünite','Noir Duvara Monte TV Konsolu','Terra Duvara Monte TV Sehpası','Sole Duvara Monte Ünite','Nord Siyah TV Ünitesi','Arco Ceviz Orta Sehpa','Marmo Traverten Orta Sehpa','Luna Yuvarlak Orta Sehpa','Linea Cam Orta Sehpa','Terra Silindir Orta Sehpa','Noir Mermer Orta Sehpa','Nord 3’lü Zigon Sehpa','Marmo 2’li Zigon Sehpa','Sole Pirinç Zigon Sehpa','Pera C Yan Sehpa','Terra Ahşap Yan Sehpa','Noir Metal Yan Sehpa','Linea Ceviz Dresuar','Marmo Traverten Dresuar','Nord Ceviz Konsol','Sole Krem Konsol','Mira Cam Kapaklı Konsol','Terra Meşe Konsol']
  },
  'Yemek Odası': {
    slug:'yemek', material:'Masif kayın / doğal meşe veya ceviz kaplama / leke tutmaz kumaş', dimensions:'Masa seçenekleri G 120–220 × D 80–100 × Y 75 cm', care:'Ahşap yüzeyleri nemli bezle silip hemen kurulayın. Sandalye kumaşında kimyasal ağartıcı kullanmayın.',
    names:['Lina Meşe Yemek Masası 160 cm','Linea Ceviz Yemek Masası','Marmo Traverten Yemek Masası','Terra Oval Yemek Masası','Noir Siyah Yemek Masası','Nord Ceviz Oval Masa','Lina Açılır Yemek Masası','Noir Açılır Konsol Masa','Terra Açılır Ceviz Masa','Marmo Açılır Taş Masa','Nord Açılır Meşe Masa','Noir Açılır Yemek Masası','Arco Yuvarlak Meşe Masa','Terra Yuvarlak Ceviz Masa','Marmo Yuvarlak Traverten Masa','Nord Yuvarlak Ahşap Masa','Noir Yuvarlak Masa','Sole Yuvarlak Taş Masa','Lina 4 Kişilik Masa Takımı','Olive 4 Kişilik Masa Takımı','Terra Yuvarlak Masa Takımı','Noir Yuvarlak Masa Takımı','Mira 4 Kişilik Masa Takımı','Noir 4 Kişilik Masa Takımı','Lina 6 Kişilik Masa Takımı','Noir 6 Kişilik Masa Takımı','Terra 6 Kişilik Masa Takımı','Olive 6 Kişilik Masa Takımı','Nord 6 Kişilik Masa Takımı','Siena Yemek Odası Bench']
  },
  'Yatak Odası': {
    slug:'yatak', material:'E1 kalite MDF / fırınlanmış ahşap / metal taşıyıcı / dokuma kumaş', dimensions:'Karyola 160×200 cm; dolap ve tamamlayıcılarda modele göre değişir', care:'Mobilyayı doğrudan güneş ve nemden koruyun. Hareketli bağlantıları yılda bir kontrol edin.',
    names:['Luna Fitilli Karyola 160×200','Olive Fitilli Karyola 160×200','Nord Meşe Karyola 160×200','Linea Ceviz Karyola 160×200','Sole Döşemeli Karyola','Noir Döşemeli Karyola','Luna Bazalı Karyola','Olive Bazalı Karyola','Nord Ahşap Bazalı Karyola','Linea Ceviz Bazalı Karyola','Sole Sandıklı Baza','Noir Sandıklı Baza','Sole 6 Kapaklı Gardırop','Nord 5 Kapaklı Gardırop','Mira Aynalı Gardırop','Noir Cam Kapaklı Gardırop','Linea Sürgülü Gardırop','Terra Sürgülü Gardırop','Sole İki Çekmeceli Komodin','Nord Ceviz Komodin','Mira Modern Komodin','Linea Ceviz Komodin','Sole 3 Çekmeceli Şifonyer','Terra 6 Çekmeceli Şifonyer','Mira Makyaj Masası','Nord Aynalı Makyaj Masası','Sole Metal Ayaklı Makyaj Masası','Luna Yatak Ucu Bench','Olive Yatak Ucu Bench','Sole 5 Parça Yatak Odası Takımı']
  },
  'Çalışma & Depolama': {
    slug:'ofis', material:'E1 kalite yonga levha veya MDF / elektrostatik boyalı metal / ergonomik file', dimensions:'Ürüne göre G 60–180 × D 30–80 × Y 45–200 cm', care:'Bağlantıları düzenli kontrol edin. Ahşap yüzeyi nemli bezle, file döşemeyi düşük emişte süpürgeyle temizleyin.',
    names:['Atlas Çekmeceli Çalışma Masası','Lina 3 Çekmeceli Çalışma Masası','Nord Bilgisayar Masası','Linea L Köşe Çalışma Masası','Mira Metal Ayaklı Çalışma Masası','Terra Dolaplı Çalışma Masası','Noir Ergonomik Ofis Koltuğu','Mira Gri Ergonomik Koltuk','Olive Ergonomik Çalışma Koltuğu','Atlas Fileli Yönetici Koltuğu','Sole Deri Yönetici Koltuğu','Noir Deri Ofis Koltuğu','Nord 5 Raflı Kitaplık','Linea Cam Kapaklı Kitaplık','Atlas Metal Kitaplık','Mira Cam Kapaklı Dolap','Olive Metal Keson','Lina 3 Kapaklı Ayakkabılık','Nord Panjurlu Ayakkabılık','Sole Minderli Ayakkabılık','Mira Portmanto','Sole Aynalı Portmanto','Olive Banyo Dolabı','Lina Çok Amaçlı Mutfak Dolabı','Nord Mikrodalga Dolabı','Linea Katlanır Masa','Sole Katlanır Plastik Masa','Atlas Servis Arabası','Lina İnce Ayakkabılık','Nord Çok Amaçlı Dolap']
  }
};

const variantSets = {
  'Oturma Grupları':[['Krem Bukle','#e6ddcf'],['Vizon Keten','#9d8d7b'],['Zeytin Dokuma','#65705a'],['Kiremit Şönil','#a9583f'],['Antrasit Dokuma','#3d403d']],
  'Salon Mobilyaları':[['Ceviz','#76513c'],['Doğal Meşe','#c7a675'],['Krem','#e5ddcf'],['Antrasit','#40413e'],['Ceviz–Krem','#9b7a5c']],
  'Yemek Odası':[['Doğal Meşe','#c59b63'],['Ceviz','#6f4b38'],['Krem–Ceviz','#b49b7b'],['Siyah Meşe','#353632'],['Traverten','#d8c8ae']],
  'Yatak Odası':[['Krem–Ceviz','#c3a98a'],['Doğal Meşe','#c4a06f'],['Zeytin–Ceviz','#68705a'],['Antrasit–Ceviz','#494a47'],['Vizon–Meşe','#9b8975']],
  'Çalışma & Depolama':[['Ceviz–Siyah','#624b3b'],['Doğal Meşe–Beyaz','#cbb593'],['Antrasit–Ceviz','#474946'],['Zeytin–Meşe','#65705a'],['Tam Beyaz','#e5e3dd']]
};

const products=[]; let pid=1;
Object.entries(catalog).forEach(([category,group],categoryIndex)=>group.names.forEach((name,index)=>{
  const basePrices=[8999,3499,4999,5999,2999],priceSpans=[52000,30000,65000,80000,26000];
  const price=basePrices[categoryIndex]+((index*1703+categoryIndex*5431)%priceSpans[categoryIndex]); const discounted=(index+categoryIndex)%5===0;
  const assetStem=`${group.slug}-${String(index+1).padStart(2,'0')}`;
  products.push({id:pid++,name,category,image:`assets/furniture/variants/${assetStem}-v1.webp`,price,oldPrice:discounted?Math.round(price*1.22):null,rating:(4.6+((index+categoryIndex)%4)*.1).toFixed(1),reviews:57+((index*149+categoryIndex*233)%3100),badge:index%9===0?'ÇOK SEVİLEN':discounted?'%18 İNDİRİM':index%7===0?'YENİ':'',fast:index%4!==0,popular:index%6===0,material:group.material,dimensions:group.dimensions,care:group.care,desc:`${name}; dayanıklı iskelet, günlük kullanım konforu ve zamansız çizgiyi bir araya getiren Viento mobilya koleksiyonunun karakterli parçalarından biridir. Ölçü, malzeme ve kullanım deneyimi birlikte değerlendirilerek hazırlanmıştır.`,variants:variantSets[category].map((v,i)=>({name:v[0],hex:v[1],image:`assets/furniture/variants/${assetStem}-v${i+1}.webp`,sku:`VNT-${String(categoryIndex+1).padStart(2,'0')}${String(index+1).padStart(2,'0')}-${i+1}`,stock:3+((index+i*5)%18)}))});
}));

function readStoreJSON(key,fallback){try{return JSON.parse(localStorage.getItem(key)||JSON.stringify(fallback))}catch{return fallback}}
const remoteProducts=Array.isArray(window.VientoRemoteProducts)&&window.VientoRemoteProducts.length?window.VientoRemoteProducts:null;
if(remoteProducts)products.splice(0,products.length,...remoteProducts);
const adminOverrides=remoteProducts?{}:readStoreJSON('viento-admin-overrides',{});
products.forEach(product=>{
  const override=adminOverrides[product.id];
  if(!override)return;
  const seededImage=product.image,seededVariants=product.variants.map(v=>({...v}));
  Object.assign(product,override);
  const isLegacyImage=value=>!value||/^assets\/furniture\/[^/]+\.jpg$/i.test(value);
  if(isLegacyImage(override.image))product.image=seededImage;
  product.variants=seededVariants.map((seed,i)=>{
    const saved=override.variants?.[i]||{},clean={...saved};
    delete clean.filter;
    return{...seed,...clean,image:saved.filter||isLegacyImage(saved.image)?seed.image:saved.image};
  });
});
if(!remoteProducts)readStoreJSON('viento-admin-custom-products',[]).forEach(product=>products.push(product));
window.VientoAdminSeed=products;
function variantImage(product,variant){return variant?.image||product.image}

const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)], money=n=>new Intl.NumberFormat('tr-TR').format(n)+' TL';
const state={category:'Tümü',maxPrice:100000,discount:false,fast:false,popular:false,sort:'featured',visible:24,search:'',selectedProduct:null,selectedVariant:0,detailQty:1,gridView:+localStorage.getItem('viento-grid-view')||4,favorites:new Set(JSON.parse(localStorage.getItem('viento-favs')||'[]')),compare:new Set(JSON.parse(localStorage.getItem('viento-compare')||'[]').slice(0,3)),recent:JSON.parse(localStorage.getItem('viento-recent')||'[]').slice(0,8),cart:JSON.parse(localStorage.getItem('viento-cart')||'[]')};

function renderCatalogProofs(){const activeProducts=products.filter(product=>product.active!==false),variantTotal=activeProducts.reduce((total,product)=>total+(product.variants?.length||0),0),seating=activeProducts.filter(product=>product.category==='Oturma Grupları'),seatingVariants=seating.reduce((total,product)=>total+(product.variants?.length||0),0);if($('#catalogProof'))$('#catalogProof').textContent=`${activeProducts.length} mobilya · ${variantTotal} gerçek renk varyasyonu`;if($('#variantProof'))$('#variantProof').textContent=`${variantTotal} VARYASYON`;if($('#shopCatalogProof'))$('#shopCatalogProof').textContent=`${activeProducts.length} MOBİLYA · ${variantTotal} VARYASYON`;if($('#seatingProof'))$('#seatingProof').textContent=`${seating.length} tasarım · ${seatingVariants} renk seçeneği`;$$('[data-category-count]').forEach(element=>{element.textContent=`${activeProducts.filter(product=>product.category===element.dataset.categoryCount).length} ürün`})}

function filtered(){let list=products.filter(p=>p.active!==false&&(state.category==='Tümü'||p.category===state.category)&&p.price<=state.maxPrice&&(!state.discount||p.oldPrice)&&(!state.fast||p.fast)&&(!state.popular||p.popular)&&(!state.search||(`${p.name} ${p.category}`).toLocaleLowerCase('tr').includes(state.search.toLocaleLowerCase('tr'))));if(state.sort==='low')list.sort((a,b)=>a.price-b.price);if(state.sort==='high')list.sort((a,b)=>b.price-a.price);if(state.sort==='rating')list.sort((a,b)=>b.rating-a.rating);if(state.sort==='new')list.sort((a,b)=>b.id-a.id);return list}
function colorDots(p){return p.variants.map(v=>`<i title="${v.name}" style="background:${v.hex}"></i>`).join('')}
function card(p){return `<article class="product-card" data-product="${p.id}" tabindex="0" aria-label="${p.name} ürününü incele"><div class="product-image"><img loading="lazy" src="${p.image}" alt="${p.name}">${p.badge?`<span class="badge ${p.oldPrice?'sale-badge':''}">${p.badge}</span>`:''}<button class="fav ${state.favorites.has(p.id)?'active':''}" data-fav="${p.id}" aria-label="Favoriye ekle">${state.favorites.has(p.id)?'♥':'♡'}</button><button class="compare-toggle ${state.compare.has(p.id)?'active':''}" data-compare="${p.id}" aria-label="Karşılaştırmaya ekle">⇄</button><button class="quick-btn" data-quick="${p.id}">Hızlı incele <span>↗</span></button></div><div class="product-meta"><div class="product-meta-top"><span class="product-category">${p.category}</span>${p.fast?'<span class="fast-delivery">Hızlı teslimat</span>':''}</div><h3>${p.name}</h3><div class="rating">★★★★★ <span>${p.rating} (${p.reviews})</span></div><div class="price">${money(p.price)} ${p.oldPrice?`<del>${money(p.oldPrice)}</del>`:''}<small>6 × ${money(Math.round(p.price/6))}</small></div><div class="product-colors">${colorDots(p)}<small>${p.variants.length} renk</small></div></div></article>`}
function render(){const list=filtered(),shown=list.slice(0,state.visible);$('#productGrid').classList.toggle('grid-three',state.gridView===3);$('#productGrid').innerHTML=shown.map(card).join('');$('#resultCount').textContent=`${list.length} mobilya · ${list.length*5} varyasyon`;$('#loadMore').style.display=shown.length<list.length?'block':'none';$('#loadMore span').textContent=`${shown.length} / ${list.length}`;$('#activeFilterCount').textContent=[state.category!=='Tümü',state.discount,state.fast,state.popular,state.maxPrice<100000].filter(Boolean).length;$$('[data-grid-view]').forEach(b=>b.classList.toggle('active',+b.dataset.gridView===state.gridView));bindCards()}
function bindCards(){$$('[data-fav]').forEach(b=>b.onclick=e=>{e.stopPropagation();toggleFav(+b.dataset.fav)});$$('[data-compare]').forEach(b=>b.onclick=e=>{e.stopPropagation();toggleCompare(+b.dataset.compare)});$$('[data-quick]').forEach(b=>b.onclick=e=>{e.stopPropagation();openProduct(+b.dataset.quick)});$$('[data-product]').forEach(c=>{c.onclick=e=>{if(!e.target.closest('button'))openProduct(+c.dataset.product)};c.onkeydown=e=>{if(e.key==='Enter')openProduct(+c.dataset.product)}})}
function setCategory(cat){state.category=cat;state.visible=24;$$('[data-chip]').forEach(b=>b.classList.toggle('active',b.dataset.chip===cat));$$('input[name=cat]').forEach(x=>x.checked=x.value===cat);render();$('#shop').scrollIntoView({behavior:'smooth'})}
function toggleFav(id){state.favorites.has(id)?state.favorites.delete(id):state.favorites.add(id);localStorage.setItem('viento-favs',JSON.stringify([...state.favorites]));$('#favCount').textContent=state.favorites.size;render();toast(state.favorites.has(id)?'Favorilere eklendi':'Favorilerden çıkarıldı')}
function toggleCompare(id){if(state.compare.has(id))state.compare.delete(id);else if(state.compare.size>=3){toast('En fazla 3 ürünü karşılaştırabilirsiniz');return}else state.compare.add(id);localStorage.setItem('viento-compare',JSON.stringify([...state.compare]));renderCompareBar();render();toast(state.compare.has(id)?'Karşılaştırmaya eklendi':'Karşılaştırmadan çıkarıldı')}
function renderCompareBar(){const selected=[...state.compare].map(id=>products.find(p=>p.id===id)).filter(Boolean);$('#compareCount').textContent=selected.length;$('#compareThumbs').innerHTML=selected.map(p=>`<button data-compare-remove="${p.id}" title="${p.name}"><img src="${p.image}" alt=""><span>${p.name}</span><i>×</i></button>`).join('')+Array.from({length:Math.max(0,3-selected.length)},()=>'<span class="compare-empty-slot">＋</span>').join('');$('#compareBar').classList.toggle('active',selected.length>0);$$('[data-compare-remove]').forEach(b=>b.onclick=()=>toggleCompare(+b.dataset.compareRemove));$('#compareOpen').disabled=selected.length<2}
function openCompare(){const selected=[...state.compare].map(id=>products.find(p=>p.id===id)).filter(Boolean);if(selected.length<2)return toast('Karşılaştırmak için en az 2 ürün seçin');const rows=[['Fiyat',p=>money(p.price)],['Kategori',p=>p.category],['Ölçüler',p=>p.dimensions],['Malzeme',p=>p.material],['Renk seçeneği',p=>`${p.variants.length} renk`],['Teslimat',p=>p.fast?'3–7 iş günü':'7–21 iş günü'],['Garanti',()=> '2 yıl'],['Değerlendirme',p=>`${p.rating} / 5 (${p.reviews})`]];$('#compareTable').innerHTML=`<div class="compare-grid compare-products"><span></span>${selected.map(p=>`<article><button data-compare-remove="${p.id}">×</button><img src="${p.image}" alt=""><small>${p.category}</small><h3>${p.name}</h3><strong>${money(p.price)}</strong><button class="btn primary" data-compare-cart="${p.id}">Sepete ekle</button></article>`).join('')}</div>${rows.map(r=>`<div class="compare-grid compare-row"><b>${r[0]}</b>${selected.map(p=>`<span>${r[1](p)}</span>`).join('')}</div>`).join('')}`;$('#compareModal').classList.add('active');$('#overlay').classList.add('active');document.body.style.overflow='hidden';$$('#compareTable [data-compare-remove]').forEach(b=>b.onclick=()=>{toggleCompare(+b.dataset.compareRemove);openCompare()});$$('[data-compare-cart]').forEach(b=>b.onclick=()=>{closeAll();openProduct(+b.dataset.compareCart)})}
function openPanel(panel){$('#overlay').classList.add('active');panel.classList.add('active');panel.setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}
function closeAll(){$$('.drawer,.quick-view,.filters,.compare-modal').forEach(x=>{x.classList.remove('active');x.setAttribute('aria-hidden','true')});$('#overlay').classList.remove('active');document.body.style.overflow='';if(location.hash.startsWith('#product-'))history.replaceState(null,'','#shop')}
function renderVariant(){const p=state.selectedProduct,v=p.variants[state.selectedVariant];$('#qvImage').src=variantImage(p,v);$('#qvImage').style.removeProperty('filter');$('#selectedColor').textContent=v.name;$('#variantSku').textContent=`Ürün kodu: ${v.sku} · ${v.stock} adet stokta`;$$('[data-variant]').forEach((b,i)=>b.classList.toggle('active',i===state.selectedVariant));$$('[data-thumb]').forEach((b,i)=>b.classList.toggle('active',i===state.selectedVariant));}
function openProduct(id){const p=products.find(x=>x.id===id);if(!p)return;history.replaceState(null,'',`#product-${id}`);state.selectedProduct=p;state.selectedVariant=0;state.detailQty=1;state.recent=[id,...state.recent.filter(x=>x!==id)].slice(0,8);localStorage.setItem('viento-recent',JSON.stringify(state.recent));$('#detailQty').textContent='1';$('#qvImage').src=variantImage(p,p.variants[0]);$('#qvImage').alt=p.name;$('#qvBadge').textContent=p.badge;$('#qvCategory').textContent=p.category;$('#qvBreadcrumb').textContent=`Ana Sayfa / ${p.category} / ${p.name}`;$('#qvTitle').textContent=p.name;$('#qvRating').innerHTML=`<span>★★★★★</span> ${p.rating} · <u>${p.reviews} değerlendirme</u>`;$('#qvPrice').innerHTML=`${money(p.price)} ${p.oldPrice?`<del>${money(p.oldPrice)}</del><small>KDV dahil</small>`:'<small>KDV dahil</small>'}`;$('#installmentLine').innerHTML=`Peşin fiyatına 6 taksit · <b>aylık ${money(Math.round(p.price/6))}</b>`;$('#qvDescription').textContent=p.desc;$('#qvSwatches').innerHTML=p.variants.map((v,i)=>`<button class="swatch ${i===0?'active':''}" data-variant="${i}" style="--sw:${v.hex}" aria-label="${v.name}" title="${v.name}"></button>`).join('');$('#qvThumbs').innerHTML=p.variants.map((v,i)=>`<button data-thumb="${i}" class="${i===0?'active':''}"><img src="${variantImage(p,v)}" alt="${p.name} ${v.name}"><span>${v.name}</span></button>`).join('');$('#qvSpecs').innerHTML=`<div><dt>Malzeme</dt><dd>${p.material}</dd></div><div><dt>Ölçü</dt><dd>${p.dimensions}</dd></div><div><dt>Renk seçeneği</dt><dd>${p.variants.length} farklı renk</dd></div><div><dt>Garanti</dt><dd>2 yıl</dd></div><div><dt>Menşei</dt><dd>Türkiye</dd></div>`;$('#qvCare').textContent=p.care;$('#qvFavorite').textContent=state.favorites.has(p.id)?'♥ Favorilerde':'♡ Favorilere ekle';$('#qvCompare').textContent=state.compare.has(p.id)?'✓ Karşılaştırmada':'⇄ Karşılaştır';$('#deliveryEstimateResult').textContent='';$$('[data-variant]').forEach(b=>b.onclick=()=>{state.selectedVariant=+b.dataset.variant;renderVariant()});$$('[data-thumb]').forEach(b=>b.onclick=()=>{state.selectedVariant=+b.dataset.thumb;renderVariant()});$('#qvAdd').onclick=addSelected;$('#qvFavorite').onclick=()=>{toggleFav(p.id);$('#qvFavorite').textContent=state.favorites.has(p.id)?'♥ Favorilerde':'♡ Favorilere ekle'};$('#qvCompare').onclick=()=>{toggleCompare(p.id);$('#qvCompare').textContent=state.compare.has(p.id)?'✓ Karşılaştırmada':'⇄ Karşılaştır'};renderVariant();openPanel($('#quickView'))}
function addSelected(){const p=state.selectedProduct,v=p.variants[state.selectedVariant],key=`${p.id}-${state.selectedVariant}`,found=state.cart.find(x=>(x.key||`${x.id}-0`)===key);if(found)found.qty+=state.detailQty;else state.cart.push({key,id:p.id,variant:state.selectedVariant,qty:state.detailQty});saveCart();closeAll();openCart();toast(`${v.name} varyasyonu sepete eklendi`)}
function saveCart(){localStorage.setItem('viento-cart',JSON.stringify(state.cart));renderCart()}
function renderCart(){state.cart=state.cart.filter(x=>products.some(p=>p.id===x.id));const count=state.cart.reduce((n,x)=>n+x.qty,0),subtotal=state.cart.reduce((n,x)=>n+products.find(p=>p.id===x.id).price*x.qty,0);$('#cartCount').textContent=count;$('#mobileCartCount').textContent=count;$('#cartTitleCount').textContent=`(${count})`;$('#cartSubtotal').textContent=money(subtotal);$('#shippingBar').style.width=Math.min(100,subtotal/25000*100)+'%';$('#shippingText').innerHTML=subtotal>=25000?'Ücretsiz teslimatı kazandınız! 🎉':`Ücretsiz teslimat için <b>${money(25000-subtotal)}</b> daha ekleyin.`;$('#cartItems').innerHTML=state.cart.map(x=>{const p=products.find(y=>y.id===x.id),vi=x.variant||0,v=p.variants[vi],key=x.key||`${x.id}-0`;return `<div class="cart-item"><img src="${variantImage(p,v)}" alt="${p.name} ${v.name}"><div><h4>${p.name}</h4><small>${v.name} · ${v.sku}</small><div class="qty"><button data-qty="${key}" data-d="-1">−</button><span>${x.qty}</span><button data-qty="${key}" data-d="1">+</button></div><button class="remove" data-remove="${key}">Kaldır</button></div><strong>${money(p.price*x.qty)}</strong></div>`}).join('');$('#cartEmpty').style.display=count?'none':'block';$('#cartFooter').style.display=count?'block':'none';$$('[data-qty]').forEach(b=>b.onclick=()=>changeQty(b.dataset.qty,+b.dataset.d));$$('[data-remove]').forEach(b=>b.onclick=()=>{state.cart=state.cart.filter(x=>(x.key||`${x.id}-0`)!==b.dataset.remove);saveCart()})}
function changeQty(key,d){const x=state.cart.find(x=>(x.key||`${x.id}-0`)===key);if(!x)return;x.qty+=d;if(x.qty<1)state.cart=state.cart.filter(y=>y!==x);saveCart()}
function openCart(){openPanel($('#cartDrawer'))}
const safeText=value=>String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
let customerAccount=null,authMode='login',accountLoading=false;
function setAccountMessage(message,type=''){$('#accountMessage').textContent=message||'';$('#accountMessage').className=`account-message ${type}`}
function orderStage(status){if(status==='Teslim edildi')return 4;if(status==='Gönderildi')return 3;if(['Hazırlanıyor','Ödendi'].includes(status))return 2;return 1}
function renderCustomerOrders(orders=[]){
  const container=$('#accountOrders');
  if(!orders.length){container.innerHTML='<div class="account-empty">Henüz siparişiniz yok. İlk Viento parçanızı keşfedin.</div>';return}
  container.innerHTML=orders.map(order=>{const stage=orderStage(order.status),cancelled=order.status==='İptal',provider=order.payment_provider==='paytr_demo'?'PayTR demo':'iyzico demo';return`<article class="account-order"><div class="account-order-head"><span><b>#${safeText(order.order_id)}</b><small>${new Intl.DateTimeFormat('tr-TR',{day:'numeric',month:'long',year:'numeric'}).format(new Date(order.date))} · ${safeText(order.payment)}</small></span><strong>${money(Number(order.total))}</strong></div>${cancelled?'<div class="account-tracking"><b>Sipariş iptal edildi</b><span>Ekibimiz sizinle iletişime geçecek.</span></div>':`<div class="order-status-line">${['Sipariş alındı','Hazırlanıyor','Gönderildi','Teslim edildi'].map((label,i)=>`<span class="${i<stage?'done':''}">${label}</span>`).join('')}</div>`}${order.tracking_number?`<div class="account-tracking"><span><small>KARGO</small><b>${safeText(order.tracking_company||'Kargo firması')}</b></span><span><small>TAKİP NUMARASI</small><b>${safeText(order.tracking_number)}</b></span></div>`:''}<div class="account-order-products">${Array.isArray(order.items)?order.items.reduce((sum,item)=>sum+(+item.qty||0),0):0} ürün · ${safeText(order.status)}${order.payment_reference?` · ${provider} / ${safeText(order.payment_reference)}`:''}</div></article>`}).join('')
}
function renderCustomerAddresses(addresses=[]){
  const container=$('#accountAddresses');
  container.innerHTML=addresses.length?addresses.map(address=>`<article class="account-address"><div><b>${safeText(address.title)}</b><p>${safeText(address.address)}<br>${safeText(address.district)} / ${safeText(address.city)} ${safeText(address.postcode)}</p></div>${address.is_default?'<em>VARSAYILAN</em>':'<span></span>'}<button type="button" data-delete-address="${address.id}">Adresi sil</button></article>`).join(''):'<div class="account-empty">Kayıtlı teslimat adresiniz bulunmuyor.</div>';
  $$('[data-delete-address]').forEach(button=>button.onclick=async()=>{if(!confirm('Bu adres silinsin mi?'))return;try{await window.VientoAuth.deleteCustomerAddress(button.dataset.deleteAddress);await refreshCustomerAccount();toast('Adres silindi')}catch(error){toast(error.message)}})
}
function initialsForCustomer(name){return String(name||'Viento Müşteri').split(/\s+/).filter(Boolean).slice(0,2).map(part=>part[0]).join('').toLocaleUpperCase('tr')}
function renderCustomerAccount(){
  const signed=Boolean(customerAccount?.user);$('#accountAuthView').hidden=signed;$('#accountSignedView').hidden=!signed;$('#accountBtn').classList.toggle('signed',signed);$('#accountBtnText').textContent=signed?'Hesabım':'Giriş';
  if(!signed)return;
  const profile=customerAccount.profile||{},name=profile.full_name||customerAccount.user.user_metadata?.full_name||'Viento üyesi';$('#accountName').textContent=name;$('#accountEmail').textContent=customerAccount.user.email||'';$('#accountAvatar').textContent=initialsForCustomer(name);$('#accountOrderCount').textContent=customerAccount.orders.length;$('#accountAddressCount').textContent=customerAccount.addresses.length;const profileForm=$('#customerProfileForm');profileForm.elements.full_name.value=profile.full_name||'';profileForm.elements.phone.value=profile.phone||'';renderCustomerOrders(customerAccount.orders);renderCustomerAddresses(customerAccount.addresses)
}
async function refreshCustomerAccount(){
  if(accountLoading)return customerAccount;accountLoading=true;
  try{customerAccount=await window.VientoAuth.getCustomerAccount();renderCustomerAccount();return customerAccount}catch(error){console.error(error);setAccountMessage(error.message)}finally{accountLoading=false}
}
async function openAccount(){closeAll();openPanel($('#accountDrawer'));await refreshCustomerAccount()}
function setAuthMode(mode){authMode=mode;$('#accountAuthView').classList.toggle('signup',mode==='signup');$$('[data-auth-mode]').forEach(button=>button.classList.toggle('active',button.dataset.authMode===mode));$('#customerAuthSubmit').textContent=mode==='signup'?'Üyeliğimi oluştur':'Giriş yap';$('#customerAuthForm').elements.password.autocomplete=mode==='signup'?'new-password':'current-password';setAccountMessage('')}
function prefillCheckout(){
  if(!customerAccount)return;const form=$('#checkoutForm'),profile=customerAccount.profile||{},parts=String(profile.full_name||'').trim().split(/\s+/);form.elements.email.value=customerAccount.user.email||'';form.elements.firstName.value=parts.shift()||'';form.elements.lastName.value=parts.join(' ');form.elements.phone.value=profile.phone||'';const address=customerAccount.addresses.find(item=>item.is_default)||customerAccount.addresses[0];if(address){form.elements.address.value=address.address||'';form.elements.city.value=address.city||'İstanbul';form.elements.district.value=address.district||'';form.elements.postcode.value=address.postcode||''}
}
let checkoutStep=1;
function checkoutSubtotal(){return state.cart.reduce((n,x)=>n+(products.find(p=>p.id===x.id)?.price||0)*x.qty,0)}
function renderCheckout(){const subtotal=checkoutSubtotal();$('#checkoutItems').innerHTML=state.cart.map(x=>{const p=products.find(y=>y.id===x.id),v=p.variants[x.variant||0];return`<article><img src="${variantImage(p,v)}" alt="${p.name} ${v.name}"><span><b>${p.name}</b><small>${v.name} · ${x.qty} adet</small></span><strong>${money(p.price*x.qty)}</strong></article>`}).join('');$('#checkoutSubtotal').textContent=$('#checkoutTotal').textContent=money(subtotal);$$('[data-checkout-step]').forEach(x=>x.classList.toggle('active',+x.dataset.checkoutStep===checkoutStep));$$('[data-checkout-progress]').forEach(x=>{x.classList.toggle('active',+x.dataset.checkoutProgress<=checkoutStep);x.classList.toggle('current',+x.dataset.checkoutProgress===checkoutStep)});$('#checkoutBack').style.visibility=checkoutStep===1?'hidden':'visible';$('#checkoutNext').textContent=checkoutStep===3?`${money(subtotal)} · Demo ödemeyi çalıştır`:checkoutStep===1?'Teslimata devam et':'Demo ödemeye devam et'}
async function openCheckout(){if(!state.cart.length)return toast('Sepetiniz henüz boş');if(!customerAccount?.user)await refreshCustomerAccount();if(!customerAccount?.user){await openAccount();setAccountMessage('Demo ödeme ve sipariş takibi için giriş yapın veya ücretsiz üye olun.');return}closeAll();checkoutStep=1;prefillCheckout();renderCheckout();$('#checkoutModal').classList.add('active');document.body.style.overflow='hidden'}
function closeCheckout(){$('#checkoutModal').classList.remove('active');document.body.style.overflow=''}
function validateCheckoutStep(){const step=$(`[data-checkout-step="${checkoutStep}"]`),fields=$$('input[required],select[required]').filter(x=>step.contains(x));for(const field of fields){if(!field.checkValidity()){field.reportValidity();return false}}return true}
async function completeCheckout(){if(!validateCheckoutStep())return;const form=$('#checkoutForm'),data=new FormData(form),button=$('#checkoutNext'),original=button.textContent,order={customer:`${data.get('firstName')} ${data.get('lastName')}`.trim(),email:data.get('email'),phone:data.get('phone'),city:data.get('city'),district:data.get('district'),address:data.get('address'),postcode:data.get('postcode'),items:state.cart.map(x=>({id:x.id,variant:x.variant||0,qty:x.qty})),notes:data.get('floor')||''},provider=data.get('paymentProvider'),scenario=data.get('demoScenario');button.disabled=true;button.textContent='Demo sanal POS çalışıyor…';try{const result=await window.VientoDB.demoCheckout(order,provider,scenario);if(!result.success){toast(`Demo ödeme reddedildi · ${result.reference}`);return}state.cart=[];saveCart();form.elements.demoCard.value='';form.elements.demoExpiry.value='';form.elements.demoCvv.value='';closeCheckout();form.reset();await refreshCustomerAccount();toast(`Demo ödeme başarılı · Sipariş #${result.id}`)}catch(error){console.error(error);toast(`Demo işlem tamamlanamadı: ${error.message}`)}finally{button.disabled=false;button.textContent=original}}
let toastTimer;function toast(msg){$('#toast').textContent=msg;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),2200)}
const roomProductIds=[1,37,46];
function renderRoomExperience(){const room=roomProductIds.map(id=>products.find(p=>p.id===id)).filter(Boolean);$('#roomProducts').innerHTML=room.map(p=>`<button data-room-list-product="${p.id}"><img src="${p.image}" alt=""><span><b>${p.name}</b><small>${p.category}</small></span><strong>${money(p.price)}</strong></button>`).join('');$$('[data-room-list-product]').forEach(b=>b.onclick=()=>openProduct(+b.dataset.roomListProduct))}
function renderSmartPicks(){const base=state.recent.length?state.recent[0]:1,ids=[base+7,base+31,base+62,base+94,base+121].map(id=>((id-1)%products.length)+1),list=ids.map(id=>products.find(p=>p.id===id)).filter(Boolean);$('#smartPicks').innerHTML=list.map(card).join('');bindCards()}

if($('#productGrid')){
$('#cartBtn').onclick=openCart;$('#accountBtn').onclick=openAccount;$('#mobileAccount').onclick=openAccount;$('#searchBtn').onclick=()=>openPanel($('#searchDrawer'));$('#overlay').onclick=closeAll;$$('[data-close]').forEach(b=>b.onclick=closeAll);$('#loadMore').onclick=()=>{state.visible+=24;render()};$('#sortSelect').onchange=e=>{state.sort=e.target.value;render()};$('#priceRange').oninput=e=>{$('#priceValue').textContent=money(+e.target.value)};$$('[data-grid-view]').forEach(b=>b.onclick=()=>{state.gridView=+b.dataset.gridView;localStorage.setItem('viento-grid-view',state.gridView);render()});
$('#applyFilters').onclick=()=>{const cats=$$('input[name=cat]:checked').map(x=>x.value);state.category=cats[0]||'Tümü';state.maxPrice=+$('#priceRange').value;state.discount=$('#onlyDiscount').checked;state.fast=$('#onlyFast').checked;state.popular=$('#onlyPopular').checked;state.visible=24;closeAll();render()};
$('#clearFilters').onclick=()=>{state.category='Tümü';state.maxPrice=100000;state.discount=state.fast=state.popular=false;$$('.filters input[type=checkbox]').forEach(x=>x.checked=false);$('#priceRange').value=100000;$('#priceValue').textContent='100.000 TL';render()};$('#filterToggle').onclick=()=>openPanel($('#filters'));$('#filterClose').onclick=closeAll;
$$('[data-chip]').forEach(b=>b.onclick=()=>setCategory(b.dataset.chip));$$('[data-category]').forEach(b=>b.onclick=()=>setCategory(b.dataset.category));$$('[data-nav-category]').forEach(a=>a.onclick=e=>{e.preventDefault();setCategory(a.dataset.navCategory==='Fırsatlar'?'Tümü':a.dataset.navCategory);if(a.dataset.navCategory==='Fırsatlar'){state.discount=true;render()}});$('[data-filter-preset]').onclick=e=>{e.preventDefault();state.popular=true;setCategory('Tümü')};
$('#searchInput').oninput=e=>{state.search=e.target.value;const list=filtered().slice(0,8);$('#searchResults').innerHTML=list.length?list.map(p=>`<button class="search-result" data-search-product="${p.id}"><img src="${p.image}" alt=""><span><h4>${p.name}</h4><small>${p.category} · ${p.variants.length} renk</small></span><b>${money(p.price)}</b></button>`).join(''):'<p>Aramanızla eşleşen mobilya bulunamadı.</p>';$$('[data-search-product]').forEach(b=>b.onclick=()=>{closeAll();openProduct(+b.dataset.searchProduct)})};$('#searchClear').onclick=()=>{$('#searchInput').value='';state.search='';$('#searchResults').innerHTML=''};$$('[data-search]').forEach(b=>b.onclick=()=>{$('#searchInput').value=b.dataset.search;$('#searchInput').dispatchEvent(new Event('input'))});
$('#detailMinus').onclick=()=>{state.detailQty=Math.max(1,state.detailQty-1);$('#detailQty').textContent=state.detailQty};$('#detailPlus').onclick=()=>{state.detailQty=Math.min(10,state.detailQty+1);$('#detailQty').textContent=state.detailQty};
$$('[data-accordion]').forEach(b=>b.onclick=()=>{const panel=$(`#${b.dataset.accordion}`),open=panel.classList.toggle('open');b.classList.toggle('open',open);b.querySelector('span').textContent=open?'−':'+'});
$('#zoomBtn').onclick=()=>$('#qvImage').classList.toggle('zoomed');$('#menuBtn').onclick=()=>$('#mobileNav').classList.toggle('active');$('#newsletterForm').onsubmit=e=>{e.preventDefault();e.target.reset();toast('Viento mektubuna hoş geldiniz!')};$('#checkoutBtn').onclick=openCheckout;$('#checkoutClose').onclick=closeCheckout;$('#checkoutBack').onclick=()=>{checkoutStep=Math.max(1,checkoutStep-1);renderCheckout()};$('#checkoutNext').onclick=()=>{if(!validateCheckoutStep())return;if(checkoutStep<3){checkoutStep++;renderCheckout()}else completeCheckout()};$('#checkoutForm').onsubmit=e=>e.preventDefault();$$('input[name="paymentProvider"]').forEach(input=>input.onchange=()=>{$$('.demo-provider').forEach(label=>label.classList.toggle('active',label.contains(input)&&input.checked));$('#demoCardBrand').textContent=input.value==='paytr_demo'?'PayTR demo':'iyzico demo'});
$$('[data-auth-mode]').forEach(button=>button.onclick=()=>setAuthMode(button.dataset.authMode));
$('#customerAuthForm').onsubmit=async event=>{event.preventDefault();const form=event.currentTarget,data=new FormData(form),button=$('#customerAuthSubmit');button.disabled=true;setAccountMessage(authMode==='signup'?'Üyeliğiniz oluşturuluyor…':'Giriş yapılıyor…');try{if(authMode==='signup'){const result=await window.VientoAuth.signUp({email:data.get('email'),password:data.get('password'),fullName:data.get('fullName'),phone:data.get('phone')});if(!result.session){setAccountMessage('Doğrulama bağlantısı e-posta adresinize gönderildi. Bağlantıdan sonra hesabınıza giriş yapabilirsiniz.','success');return}}else await window.VientoAuth.signIn(data.get('email'),data.get('password'));form.reset();customerAccount=null;await refreshCustomerAccount();setAccountMessage('')}catch(error){setAccountMessage(error.message)}finally{button.disabled=false}};
$('#googleAuth').onclick=async()=>{setAccountMessage('Google oturumu açılıyor…');try{await window.VientoAuth.signInWithGoogle()}catch(error){setAccountMessage(`Google girişi henüz Supabase sağlayıcı ayarı istiyor: ${error.message}`)}};
$('#customerLogout').onclick=async()=>{await window.VientoAuth.signOut();customerAccount=null;renderCustomerAccount();toast('Oturum kapatıldı')};$('#refreshAccount').onclick=()=>refreshCustomerAccount();
$('#customerProfileForm').onsubmit=async event=>{event.preventDefault();const data=new FormData(event.currentTarget);try{await window.VientoAuth.saveCustomerProfile(Object.fromEntries(data));await refreshCustomerAccount();toast('Profil bilgileri kaydedildi')}catch(error){toast(error.message)}};
$('#customerAddressForm').onsubmit=async event=>{event.preventDefault();const data=new FormData(event.currentTarget),values=Object.fromEntries(data);values.is_default=data.get('is_default')==='on';try{await window.VientoAuth.saveCustomerAddress(values);event.currentTarget.reset();event.currentTarget.elements.title.value='Ev';await refreshCustomerAccount();toast('Teslimat adresi kaydedildi')}catch(error){toast(error.message)}};
$('#compareOpen').onclick=openCompare;$('#compareClose').onclick=closeAll;$('#compareClear').onclick=()=>{state.compare.clear();localStorage.setItem('viento-compare','[]');renderCompareBar();render()};$('#qvShare').onclick=async()=>{const text=`${state.selectedProduct?.name||'Viento ürünü'} · ${location.href}`;try{if(navigator.share)await navigator.share({title:state.selectedProduct.name,text,url:location.href});else await navigator.clipboard.writeText(text);toast('Ürün bağlantısı kopyalandı')}catch{toast('Paylaşım iptal edildi')}};$('#deliveryEstimator').onsubmit=e=>{e.preventDefault();const code=$('#deliveryPostcode').value.trim();if(code.length!==5)return toast('5 haneli posta kodu girin');const days=code.startsWith('34')?'3–7':'7–14';$('#deliveryEstimateResult').innerHTML=`<b>${days} iş günü</b> içinde planlı teslimat · Kurulum seçeneği mevcut`};
$$('[data-hero-product]').forEach(b=>b.onclick=()=>openProduct(+b.dataset.heroProduct));$$('[data-room-product]').forEach(b=>b.onclick=()=>openProduct(+b.dataset.roomProduct));$$('[data-discovery-category]').forEach(c=>c.onclick=()=>setCategory(c.dataset.discoveryCategory));$$('[data-scroll-shop]').forEach(b=>b.onclick=()=>$('#shop').scrollIntoView({behavior:'smooth'}));$('#addRoomToCart').onclick=()=>{roomProductIds.forEach(id=>{const p=products.find(x=>x.id===id);if(!p)return;const key=`${id}-0`,found=state.cart.find(x=>(x.key||`${x.id}-0`)===key);found?found.qty++:state.cart.push({key,id,variant:0,qty:1})});saveCart();openCart();toast('Odadaki 3 ürün sepete eklendi')};$('#roomPlanner').onclick=()=>{$('.room-stage').classList.toggle('planning');toast($('.room-stage').classList.contains('planning')?'Oda planlama noktaları etkin':'Oda planlayıcı kapatıldı')};
$('#smartPrev').onclick=()=>$('#smartPicks').scrollBy({left:-420,behavior:'smooth'});$('#smartNext').onclick=()=>$('#smartPicks').scrollBy({left:420,behavior:'smooth'});$$('[data-service]').forEach(b=>b.onclick=()=>toast(`${b.closest('article').querySelector('h3').textContent} talebiniz için form hazırlandı`));$('#mobileSearch').onclick=()=>openPanel($('#searchDrawer'));$('#mobileCart').onclick=openCart;document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();openPanel($('#searchDrawer'));setTimeout(()=>$('#searchInput').focus(),200)}if(e.key==='Escape'){closeAll();closeCheckout()}});
$('#favBtn').onclick=()=>{const favs=products.filter(p=>state.favorites.has(p.id));closeAll();$('#productGrid').innerHTML=favs.length?favs.map(card).join(''):'<p class="empty-state">Henüz favoriniz yok.</p>';$('#resultCount').textContent=`${favs.length} favori`;$('#loadMore').style.display='none';$('#shop').scrollIntoView({behavior:'smooth'});bindCards()};
$('#favCount').textContent=state.favorites.size;renderCatalogProofs();renderCart();renderCompareBar();renderRoomExperience();renderSmartPicks();render();
const revealObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('revealed');revealObserver.unobserve(entry.target)}}),{threshold:.08});$$('.section,.trend-strip,.story,.service-suite').forEach(el=>{el.classList.add('reveal-ready');revealObserver.observe(el)});
setTimeout(()=>$$('.reveal-ready').forEach(el=>el.classList.add('revealed')),700);
const adminContent=readStoreJSON('viento-admin-content',{});if(adminContent.announcementText){const bar=$('.topbar span');bar.textContent=adminContent.announcementText;if(adminContent.announcementActive===false)bar.closest('.topbar').style.display='none'}if(adminContent.heroEyebrow)$('.hero .eyebrow').textContent=adminContent.heroEyebrow;if(adminContent.heroTitle)$('.hero h1').innerHTML=adminContent.heroTitle.replace(', ', ',<br>');if(adminContent.heroDescription)$('.hero-copy>p:not(.eyebrow)').textContent=adminContent.heroDescription;
window.VientoAuth.onAuthStateChange(()=>{customerAccount=null;setTimeout(()=>refreshCustomerAccount(),0)});refreshCustomerAccount();if(location.hash==='#account')setTimeout(openAccount,100);
if(location.hash.startsWith('#product-'))setTimeout(()=>openProduct(+location.hash.replace('#product-','')),0);
}
