create table if not exists public.viento_newsletter_subscribers (
  id bigint generated by default as identity primary key,
  email text not null unique,
  status text not null default 'active' check (status in ('active', 'unsubscribed')),
  source text not null default 'storefront' check (char_length(source) between 1 and 40),
  consented_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint viento_newsletter_email_check check (
    char_length(email) between 5 and 320
    and email = lower(btrim(email))
    and email ~ '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$'
  )
);

create table if not exists public.viento_service_requests (
  id bigint generated by default as identity primary key,
  service text not null check (service in ('consultation', 'sample', 'delivery')),
  name text not null check (char_length(btrim(name)) between 2 and 160),
  email text not null,
  phone text not null check (char_length(btrim(phone)) between 7 and 40),
  city text not null default '' check (char_length(city) <= 100),
  message text not null check (char_length(btrim(message)) between 10 and 1500),
  status text not null default 'new' check (status in ('new', 'contacted', 'closed')),
  user_id uuid default auth.uid() references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint viento_service_email_check check (
    char_length(email) between 5 and 320
    and email = lower(btrim(email))
    and email ~ '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$'
  )
);

alter table public.viento_newsletter_subscribers enable row level security;
alter table public.viento_service_requests enable row level security;

revoke all on table public.viento_newsletter_subscribers from anon, authenticated;
revoke all on table public.viento_service_requests from anon, authenticated;
grant insert on table public.viento_newsletter_subscribers to anon, authenticated;
grant insert on table public.viento_service_requests to anon, authenticated;
grant select, update, delete on table public.viento_newsletter_subscribers to authenticated;
grant select, update, delete on table public.viento_service_requests to authenticated;
grant usage, select on sequence public.viento_newsletter_subscribers_id_seq to anon, authenticated;
grant usage, select on sequence public.viento_service_requests_id_seq to anon, authenticated;

drop policy if exists "newsletter public signup" on public.viento_newsletter_subscribers;
create policy "newsletter public signup"
on public.viento_newsletter_subscribers
for insert
to anon, authenticated
with check (status = 'active' and source = 'storefront');

drop policy if exists "newsletter admin read" on public.viento_newsletter_subscribers;
create policy "newsletter admin read"
on public.viento_newsletter_subscribers
for select
to authenticated
using ((select public.viento_is_admin()));

drop policy if exists "newsletter admin update" on public.viento_newsletter_subscribers;
create policy "newsletter admin update"
on public.viento_newsletter_subscribers
for update
to authenticated
using ((select public.viento_is_admin()))
with check ((select public.viento_is_admin()));

drop policy if exists "newsletter admin delete" on public.viento_newsletter_subscribers;
create policy "newsletter admin delete"
on public.viento_newsletter_subscribers
for delete
to authenticated
using ((select public.viento_is_admin()));

drop policy if exists "service request public create" on public.viento_service_requests;
create policy "service request public create"
on public.viento_service_requests
for insert
to anon, authenticated
with check (status = 'new' and user_id is not distinct from (select auth.uid()));

drop policy if exists "service request admin read" on public.viento_service_requests;
create policy "service request admin read"
on public.viento_service_requests
for select
to authenticated
using ((select public.viento_is_admin()));

drop policy if exists "service request admin update" on public.viento_service_requests;
create policy "service request admin update"
on public.viento_service_requests
for update
to authenticated
using ((select public.viento_is_admin()))
with check ((select public.viento_is_admin()));

drop policy if exists "service request admin delete" on public.viento_service_requests;
create policy "service request admin delete"
on public.viento_service_requests
for delete
to authenticated
using ((select public.viento_is_admin()));

comment on table public.viento_newsletter_subscribers is 'Consent-based Viento Market newsletter signups.';
comment on table public.viento_service_requests is 'Customer consultation, sample, and delivery requests.';
